 import * as t from 'assert';
import { State } from '../../src/state';
import { Context } from '../../src/common';
import { Token } from '../../src/token';
import { validateRegExp, RegexpState } from '../../src/runtime/validateRegExp';
//import { RegexpState } from '../../src/runtime/common';

describe('Lexer - Regular expressions', () => {

  function passOrFail(name: string, opts: any): any {
      function test(name: string, context: Context): any {
          it(name, () => {
              const state = validateRegExp(opts.source, context);
              console.log(state)
              if (state === RegexpState.ALWAYS_BAD) {
                t.equal(state, RegexpState.ALWAYS_BAD);
              } else {
                t.equal(state, RegexpState.ALWAYS_GOOD);
              }
          });
      }

      test(`${name} `, Context.Empty);
  }

  function pass(name: string, opts: any): any {
    it(name, () => {
      t.equal(validateRegExp(opts.source, opts.context), RegexpState.ALWAYS_GOOD);
    });
  }

  function fail(name: string, opts: any): any {
        it(name, () => {
          t.equal(validateRegExp(opts.source, opts.context), RegexpState.ALWAYS_BAD);
        });
  }

  describe('Unicode', () => {

    const InValidUnicodeCases = [

      "(/u",
      "(?=foo/u",
      "(?/u",
      "(?=foo/u",
      "(?!foo/u",
      "(?=a)*/u",
      "(?=a)+/u",
      "(?=a)?/u",
      "(?=a){/u",
      "(?=a){}/u",

      "(?=a){a}/u",
      "(?=a){1}/u",
      "(?=a){1,}/u",
      "(?=a){1,2}/u",
      // "a{/u",
      // "a{}/u",
      "a{a}/u",
      //"a{1/u",
      // "a{2,1/u",
      //"a{1,?/u"
      "${1,2/u",
      "${1,2}/u",
      "${2,1}/u",
      "\\1/u",
      "\\2(a)(/u",
      "(?:a)\\1/u",
      "(a)\\2/u",
      "(?:a)\\2/u",
      "(a)(a)(a)(a)(a)(a)(a)(a)(a)(a)\\11/u",
      "(?a/u",
      "(?a)/u",
      "(?:/u",
      "(?:a/u",
      "(:a/u",
      "\\c1/u",
      "\\c/u",
      "\\u/u",
      "\\u1/u",
      "\\u12/u",
      "\\u123/u",
      "\\u{/u",
      "\\u{z/u",
      "\\u{20/u",
      "\\377/u",
      "\\400/u",
      "\\a/u",
      "[b-a]/u",
      "[a-b--+]/u",
      "[\\c1]/u",
      "[\\c]/u",
      "[\\x]/u",
      "[\\xz]/u",
      "[\\x1]/u",
      "[\\u]/u",
      "[\\u1]/u",
      "[\\u12]/u",
      "[\\u123]/u",
      "[\\u{]/u",
      "[\\u{z]/u",
      "[\\u{20]/u",
      "[\\u{110000}]/u",
      "[\\77]/u",
      "[\\377]/u",
      "[\\400]/u",
      "[\\a]/u",
      "[\\d-\\uFFFF]/u",
      "[\\D-\\uFFFF]/u",
      "[\\s-\\uFFFF]/u",
      "[\\S-\\uFFFF]/u",
      "[\\w-\\uFFFF]/u",
      "[\\W-\\uFFFF]/u",
      "[\\u0000-\\d]/u",
      "[\\u0000-\\D]/u",
      "[\\u0000-\\s]/u",
      "[\\u0000-\\S]/u",
      "[\\u0000-\\w]/u",
      "[\\u0000-\\W]/u",
      "[\\u0001-\\u0000]/u",
      //"[\\u{2}-\\u{1}]/u",
      "[\\u{2-\\u{1}]/u",
      "[\\a-\\z]/u",
      "[\\z-\\a]/u",
      "[0-9--+]/u",
      //"[🌸-🌷]/u",
      "[\\c_]/u",
      "[\\c0-\\u001f]/u",
      "[\\d][\\12-\\14]{1,}[^\\d]/u",
      "[\\u0000-\\u0001]/u",
      "[\\u0001-\\u0000]/u",
      "[\\u{2}-\\u{1}]/",
      "[\\a-\\z]/u",
      "[\\z-\\a]/u",
      "[0-9--+]/u",
      "[\\c-a]/u",
      "[\\c0-]/u",
      "[\\c_]/u",
      // "[🌷-🌸]/u",
      "[\\u0000-\\ud83c\\udf38-\\u0000]/",
      "[🌸-🌷]/",
      // "[🌸-🌷]/u",
      "[\\d][\\12-\\14]{1,}[^\\d]/u",
      "\\k/u",
      //"\\k<a>/u",
      "(?<a>a)\\k</",
      "(?<a>a)\\k</u",
      "(?<a>a)\\k<a/u",
      "(?<a>a)\\k<b>/",
      "(?<a>a)\\k<b>/u",
      "(?<a>a)(?<a>a)/u",
      "(?<a>a)(?<b>a)/u",
      "(?<11>a)\\k<11>/u",
      "\\p/u",
      "\\p{/u",
//      "\\p{General_Category=}/u",
       "(?<a)/u",
        "(?<!a)/u",
       "(?<=a)?/u",
       "(?<=a)?/",
       "(?<=a)*/u",
       "(?<=a){1}/u",
       "(?<!a)?/u",
       "(?<!a){1}/u",
       "(?<a)/u",
       //"(?<=a)/u",
       // "(?<!a)/u",
       "(?</",
       "\\k/u",
       "(?<a>a)\\k</",
       "(?<a>a)\\k</u",
       "(?<a>a)\\k<a/",
       "(?<a>a)\\k<a/u",
       "(?<a>a)\\2/u",
       "(?<a>a)(?<a>a)/u",
       "(?<a>a)(?<\\u{61}>a)/u",
       "(?<☀>a)\\k<☀>/u",
       "(?<\\u0020>a)\\k<\\u0020>/u",
       "(?<\\u0061\\u0062\\u0063>a)\\k<abd>/u",
       "(?<11>a)\\k<11>/u",
       "\\p{/u",
       "\\p/u",
       "\\p{ASCII/u",
       // "\\p{General_Category}/u"
       'a{ 1}/u',
       'a{1 }/u',
       'a{1, 1}/u',
       'a{ 1, 1}/u',
       'a{1 ,1}/u',
       'a{ 1 , 1}/u',
       'a{1,1 }/u',

       'a{1, 1 }/u',
       'a{ 1, 1 }/u',
       'a{ 1 , 1 }/u',
       'foo/uu',
       'foo/uiug',
       'foo/gmumi',
       'foo/ggumi',
       'foo/myuy',
       'foo/iugyi',

       'abc\\a/u',
       'abc\\e/u',
       'abc\\g/u',
       'abc\\h/u',
       'abc\\i/u',
       'abc\\j/u',
       'abc\\k/u',
       'abc\\l/u',
       'abc\\m/u',
       'abc\\o/u',
       'abc\\p/u',
       'abc\\q/u',
       'abc\\u/u',
       'abc\\x/u',
       'abc\\y/u',
       'abc\\z/u',

       'abc\\A/u',
       'abc\\E/u',
       'abc\\F/u',
       'abc\\G/u',
       'abc\\H/u',
       'abc\\I/u',
       'abc\\J/u',
       'abc\\K/u',
       'abc\\L/u',
       'abc\\M/u',
       'abc\\N/u',
       'abc\\O/u',
       'abc\\P/u',
       'abc\\Q/u',
       'abc\\R/u',
       'abc\\T/u',
       'abc\\U/u',
       'abc\\V/u',
       'abc\\X/u',
       'abc\\Y/u',
       'abc\\Z/u',

       'abc\\adeff/u',
       'abc\\gdeff/u',
       'abc\\hdeff/u',
       'abc\\ideff/u',
       'abc\\jdeff/u',
       'abc\\kdeff/u',
       'abc\\ldeff/u',
       'abc\\mdeff/u',
       'abc\\odeff/u',
       'abc\\pdeff/u',
       'abc\\qdeff/u',
       'abc\\ydeff/u',
       'abc\\zdeff/u',

       `\\'/u`,
       `\\"/u`,
       `\\\`/u`,
       '+/u',
       '?/u',
       ')/u',
       ']/u',
       '{/u',
       '}/u',

       'a|*/u',
       'a|+/u',
       'a|?/u',
       'a|)/u',
       'a|]/u',
       'a|{/u',
       'a|}/u',

       'a(*)/u',
       'a(+)/u',
       'a(?)/u',
       'a|(])/u',
       'a|({)/u',
       'a|(})/u',

       '\\x/u',
       '\\x0/u',
       '\\x1/u',
       '\\x2/u',
       '\\x3/u',
       '\\x4/u',
       '\\x5/u',
       '\\x6/u',
       '\\x7/u',
       '\\x8/u',
       '\\x9/u',

       '\\01/u',
       'a\\02/u',
       '\\03b/u',
       'a\\04b/u',
       '(a)\\05/u',
       '\\06(b)/u',
       '(\\07)/u',
       '\\08/u',
       '\\09/u',
       '\\00/u',
       '\\0',
       'a\\0',
       '\\0b',
       'a\\0b',
       '(a)\\0',
       '\\0(b)',
       '(\\0)',
       '\\01',
       'a\\02',
       '\\03b',
       'a\\04b',
       '(a)\\05',
       '\\06(b)',
       '(\\07)',
       '\\08',
       '\\09',
       '\\00',

       '\\1(a)',
       '(a)\\1',
       '(\\1)',
       '\\1x(a)',
       '(a)x\\1',
       '(a\\1b)',
       '0\\1(a)',
       '4\\1(a)',
       '(a)|\\1',
       '\\1|(a)',
       '(\\1|a)',
       '(a|\\1)',

       //'\\2(a)/u',
      // '(a)\\3/u',
       '(\\4)/u',
       '\\5x(a)/u',
       '(a)x\\6/u',
       '(a\\7b)/u',
       '0\\8(a)/u',
      // '4\\9(a)/u',
       '(a)|\\10/u',
       '\\11|(a)/u',
       '(\\12|a)/u',
       '(a|\\13)/u',
       // 'a\\1/u',
       // '(a)\\2/u',
       // '((a))\\3/u',
       // '(((a)))\\4/u',
       // '((((a))))\\5/u',
       '(((((a)))))\\6/u',
       '((((((a))))))\\7/u',
       '(((((((a)))))))\\8/u',
       '((((((((a))))))))\\9/u',
       '(((((((((a)))))))))\\10/u',
       '((((((((((a))))))))))\\11/u',
       '(((((((((((a)))))))))))\\12/u',
       '((((((((((((a))))))))))))\\13/u',
       '(((((((((((((a)))))))))))))\\14/u',
       '((((((((((((((a))))))))))))))\\15/u',
       '(((((((((((((((a)))))))))))))))\\16/u',
       '((((((((((((((((a))))))))))))))))\\17/u',
       '(((((((((((((((((a)))))))))))))))))\\18/u',
       '((((((((((((((((((a))))))))))))))))))\\19/u',
       '(((((((((((((((((((a)))))))))))))))))))\\20/u',
       '((((((((((((((((((((a))))))))))))))))))))\\21/u',

       `\\u{00000000000000000000110000}/u`,

       `[b\\-a]/u`,

       '[\\1]/u',
       '[\\2]/u',
       '[\\3]/u',
       '[\\4]/u',
       '[\\5]/u',
       '[\\6]/u',
       '[\\7]/u',
       '[\\8]/u',
       '[\\9]/u',

       '[\\00]/u',
       '[\\01]/u',
       '[\\02]/u',
       '[\\03]/u',
       '[\\04]/u',
       '[\\05]/u',
       '[\\06]/u',
       '[\\07]/u',
       '[\\08]/u',
       '[\\09]/u',

       '[\\90]/u',
       '[\\12]/u',
       '[\\23]/u',
       '[\\34]/u',
       '[\\45]/u',
       '[\\56]/u',
       '[\\67]/u',
       '[\\78]/u',
       '[\\89]/u',
       '[\\91]/u',

       '[\\_]/u',
       '[abc\\_]/u',
       '[\\_abcd]/u',
       '[abc\\_abcd]/u',

       `[\\^`,
       `[\\$`,
       `[\\\\`,
       `[\\.`,
       `[\\*`,
       `[\\+`,
       `[\\?`,
       `[\\(`,
       `[\\)`,

       '[\\x]/u',
       '[\\x0]/u',
       '[\\x1]/u',
       '[\\x2]/u',
       '[\\x3]/u',
       '[\\x4]/u',
       '[\\x5]/u',
       '[\\x6]/u',
       '[\\x7]/u',
       '[\\x8]/u',
       '[\\x9]/u',

       `[\\u{}]/u`, `[\\u{fail}]/u`, `[\\u{afail}]/u`, `[\\u{0fail}]/u`, `[\\u{xxxx}]/u`,
       `[\\u{]/u`, `[\\u{a]/u`, `[\\u{af]/u`, `[\\u{012]/u`, `[\\u{01234]/u`, `[\\u{012345]/u`,
       `[\\u{`, `[\\u{a`, `[\\u{af`, `[\\u{123`, `[\\u{1234`, `[\\u{12345`, `[\\u{103456`,
       `[\\u{110000}]/u`, `[\\u{120000}]/u`, `[\\u{900000}]/u`, `[\\u{123456789}]/u`, `[\\u{ffffffffffffffff}]/u`,
       `[\\u{10000000000000000}]/u`,
       `[\\u{fffffffffffffffffffff}]/u`,
       //`[\\u{0000000000000000000010ffff}]/u`,
       `[\\u{00000000000000000000110000}]/u`,
       `[\\u{00000000000000000000120000}]/u`,
       `[\\u{0000000000123456789}]/u`,
       `[\\u{000000ffffffffffffffff}]/u`,
       '[x\\d-z]/u',
       '[x\\D-Z]/u',
       '[x\\s-z]/u',
       '[x\\S-S]/u',
       '[x\\w-z]/u',
       '[x\\W-Z]/u',
       '[a-\\dx]/u', '[A-\\Dx]/u', '[a-\\sx]/u', '[A-\\Sx]/u', '[a-\\wx]/u',
       '[A-\\Wx]/u',
       '[9-1]/u',
       '[x-\\uD83D\\uDE07--+]/u',
       ')/u',
       '((b', '((b)', '((b))', '(a(b', '(a(b)', '(a(b))', 'a(a(b', 'a(a(b)', 'a(a(b))',
       '(?x)/u',
       '(?:b)',
       'a(?:b)',
       '(?:b)c',
       'a(?:b)c',
       '(?:(?:b',
       '(?:(?:b)',
       '(?:(?:b))',
       '(?:a(?:b',
       '(?:a(?:b)',
       '(?:a(?:b))',
       'a(?:a(?:b',
       'a(?:a(?:b)',
       'a(?:a(?:b))',
       '(?=b)',
       'a(?=b)',
       '(?=b)c',
       'a(?=b)c',

       '(?=(?=b',
       '(?=(?=b)',
       '(?=(?=b))',
       '(?=a(?=b',
       '(?=a(?=b)',
       '(?=a(?=b))',
       'a(?=a(?=b',
       'a(?=a(?=b)',
       'a(?=a(?=b))',
       '(?!b)',
       'a(?!b)',
       '(?!b)c',
       'a(?!b)c',

       '(?!(?!b',
       '(?!(?!b)',
       '(?!(?!b))',
       '(?!a(?!b',
       '(?!a(?!b)',
       '(?!a(?!b))',
       'a(?!a(?!b',
       'a(?!a(?!b)',
       'a(?!a(?!b))',

       'a(bcde/u',
       'a(b(cde/u',
       'a(b(?:cd)e/u',
       'a(b(?:cde/u',
       'a(b(?=cd)e/u',
       'a(b(?=cde/u',
       'a(b(?!cd)e/u',
       'a(b(?!cde/u',
       'a(?:b(cd)e/u',
       'a(?:b(cde/u',
       'a(?:b(?:cd)e/u',
       'a(?:b(?:cde/u',
       'a(?:b(?=cd)e/u',
       'a(?:b(?=cde/u',
       'a(?:b(?!cd)e/u',
       'a(?:b(?!cde/u',
       'a(?=b(cd)e/u',
       'a(?=b(cde/u',
       'a(?=b(?:cd)e/u',
       'a(?=b(?:cde/u',
       'a(?=b(?=cd)e/u',
       'a(?=b(?=cde/u',
       'a(?=b(?!cd)e/u',
       'a(?=b(?!cde/u',
       'a(?!b(c)de/u',
       'a(?!b(cde/u',
       'a(?!b(?:cd)e/u',
       'a(?!b(?:cde/u',
       'a(?!b(?=cd)e/u',
       'a(?!b(?=cde/u',
       'a(?!b(?!cd)e/u',
       'a(?!b(?!cde/u',

       'abc/au',
       'abc/ub',

       './\\u0067u', './u\\u0067',

       // '\\1/u',
       // '\\2/u',
       // '\\3/u',
       // '\\4/u',
       // '\\5/u',
       // '\\6/u',
       // '\\7/u',
       // '\\8/u',
       // '\\9/u',

       '\\b*/u',
       '\\b+/u',
       '\\b?/u',
       '\\b{1}/u',
       '\\b**/u',
       '\\b++/u',
       '\\b?+/u',
       '\\b{1}+/u',
       '(?=.)**/u',
       '(?=.)++/u',
       '(?=.)?+/u',
       '(?=.){1}+/u',
       '\\B*/u',
       '\\B+/u',
       '\\B?/u',
       '\\B{1}/u',
       '\\B**/u',
       '\\B++/u',
       '\\B?+/u',
       '\\B{1}+/u',
       '(?!.)**/u',
       '(?!.)++/u',
       '(?!.)?+/u',
       '(?!.){1}+/u',

       // '0{2,1}/u',
       '^[z-a]$/u',
       'a**/u',
       'a***/u',
       'a++/u',
       'a+++/u',
       'a???/u',
       'a????/u',
       'x{1}{1,}/u',
       'x{1,2}{1}/u',
       'x{1,}{1}/u',
       'x{0,1}{1,}/u',
       //'/*a/', '/**a/',  // these are multi line comments
       '+a/u',
       '++a/u',
       '?a/u',
       '??a/u',
       '[b-ac-e]/u',
       '[a-dc-b]/u',
       '[\\db-G]/u',
       '[\\Db-G]/u',
       '[\\sb-G]/u',
       '[\\Sb-G]/u',
       '[\\wb-G]/u',
       '[\\Wb-G]/u',
       '[\\0b-G]/u',
       '[\\10b-G]/u',
       '[\\bd-G]/u',
       '[\\Bd-G]/u',
       '[\\td-G]/u',
       '[\\nd-G]/u',
       '[\\vd-G]/u',
       '[\\fd-G]/u',
       '[\\rd-G]/u',
       '[\\c0001d-G]/u',
       '[\\x0061d-G]/u',
       '[\\u0061d-G]/u',
       '[\\ad-G]/u',
       '[c-eb-a]/u',
       '[b-G\\d]/u',
       '[b-G\\D]/u',
       '[b-G\\s]/u',
       '[b-G\\S]/u',
       '[b-G\\w]/u',
       '[b-G\\W]/u',
       '[b-G\\0]/u',
       '[b-G\\10]/u',
       '[d-G\\b]/u',
       '[d-G\\B]/u',
       '[d-G\\t]/u',
       '[d-G\\n]/u',
       '[d-G\\v]/u',
       '[d-G\\f]/u',
       '[d-G\\r]/u',
       '[d-G\\c0001]/u',
       '[d-G\\x0061]/u',
       '[d-G\\u0061]/u',
       '[d-G\\a]/u',
       '\\\rn/u',

      '[abc\\Adeff]/u',
      '[abc\\Cdeff]/u',
      '[abc\\Edeff]/u',
      '[abc\\Fdeff]/u',
      '[abc\\Gdeff]/u',
      '[abc\\Hdeff]/u',
      '[abc\\Ideff]/u',
      '[abc\\Jdeff]/u',
      '[abc\\Kdeff]/u',
      '[abc\\Ldeff]/u',
      '[abc\\Mdeff]/u',
      '[abc\\Ndeff]/u',
      '[abc\\Odeff]/u',
      '[abc\\Pdeff]/u',
      '[abc\\Qdeff]/u',
      '[abc\\Rdeff]/u',
      '[abc\\Tdeff]/u',
      '[abc\\Udeff]/u',
      '[abc\\Vdeff]/u',
      '[abc\\Ydeff]/u',
      '[abc\\Zdeff]/u',

       '[abc\\adeff]/u',
       '[abc\\gdeff]/u',
       '[abc\\hdeff]/u',
       '[abc\\ideff]/u',
       '[abc\\jdeff]/u',
       '[abc\\kdeff]/u',
       '[abc\\ldeff]/u',
       '[abc\\mdeff]/u',
       '[abc\\odeff]/u',
       '[abc\\pdeff]/u',
       '[abc\\qdeff]/u',
       '[abc\\ydeff]/u',
       '[abc\\zdeff]/u',

       '[\\Aabcd]/u',
       '[\\Cabcd]/u',
       '[\\Eabcd]/u',
       '[\\Fabcd]/u',
       '[\\Gabcd]/u',
       '[\\Habcd]/u',
       '[\\Iabcd]/u',
       '[\\Jabcd]/u',
       '[\\Kabcd]/u',
       '[\\Labcd]/u',
       '[\\Mabcd]/u',
       '[\\Nabcd]/u',
       '[\\Oabcd]/u',
       '[\\Pabcd]/u',
       '[\\Qabcd]/u',
       '[\\Rabcd]/u',
       '[\\Tabcd]/u',
       '[\\Uabcd]/u',
       '[\\Vabcd]/u',
       '[\\Xabcd]/u',
       '[\\Yabcd]/u',
       '[\\Zabcd]/u',

       '[\\aabcd]/u',
       '[\\eabcd]/u',
       '[\\gabcd]/u',
       '[\\habcd]/u',
       '[\\iabcd]/u',
       '[\\jabcd]/u',
       '[\\kabcd]/u',
       '[\\labcd]/u',
       '[\\mabcd]/u',
       '[\\oabcd]/u',
       '[\\pabcd]/u',
       '[\\qabcd]/u',
       '[\\yabcd]/u',
       '[\\zabcd]/u',

      '[abc\\A]/u',
      '[abc\\E]/u',
      '[abc\\F]/u',
      '[abc\\G]/u',
      '[abc\\H]/u',
      'abc\\I]/u',
      '[abc\\J]/u',
      '[abc\\K]/u',
      '[abc\\L]/u',
      '[abc\\M]/u',
      '[abc\\N]/u',
      '[abc\\O]/u',
      '[abc\\P]/u',
      '[abc\\Q]/u',
      '[abc\\R]/u',
      '[abc\\T]/u',
      '[abc\\U]/u',
      '[abc\\V]/u',
      '[abc\\X]/u',
      '[abc\\Y]/u',
      '[abc\\Z]/u',

       '[abc\\a]/u',
       '[abc\\e]/u',
       '[abc\\g]/u',
       '[abc\\h]/u',
       '[abc\\i]/u',
       '[abc\\j]/u',
       '[abc\\k]/u',
       '[abc\\l]/u',
       '[abc\\m]/u',
       '[abc\\o]/u',
       '[abc\\p]/u',
       '[abc\\q]/u',
       '[abc\\u]/u',
       '[abc\\x]/u',
       '[abc\\y]/u',
       '[abc\\z]/u',

       '[\\A]/u',
       '[\\E]/u',
       '[\\F]/u',
       '[\\G]/u',
       '[\\H]/u',
       '[\\I]/u',
       '[\\J]/u',
       '[\\K]/u',
       '[\\L]/u',
       '[\\M]/u',
       '[\\N]/u',
       '[\\O]/u',
       '[\\P]/u',
       '[\\Q]/u',
       '[\\R]/u',
       '[\\T]/u',
       '[\\U]/u',
       '[\\V]/u',
       '[\\X]/u',
       '[\\Y]/u',
       '[\\Z]/u',

       '[\\a]/u',
       '[\\e]/u',
       '[\\g]/u',
       '[\\h]/u',
       '[\\i]/u',
       '[\\j]/u',
       '[\\k]/u',
       '[\\l]/u',
       '[\\m]/u',
       '[\\o]/u',
       '[\\p]/u',
       '[\\q]/u',
       '[\\u]/u',
       '[\\x]/u',
       '[\\y]/u',
       '[\\z]/u',
       // '\\/u',
       // 'a|\\/u',

       'abc\\Adeff/u',
       'abc\\Cdeff/u',
       'abc\\Edeff/u',
       'abc\\Fdeff/u',
       'abc\\Gdeff/u',
       'abc\\Hdeff/u',
       'abc\\Ideff/u',
       'abc\\Jdeff/u',
       'abc\\Kdeff/u',
       'abc\\Ldeff/u',
       'abc\\Mdeff/u',
       'abc\\Ndeff/u',
       'abc\\Odeff/u',
       'abc\\Pdeff/u',
       'abc\\Qdeff/u',
       'abc\\Rdeff/u',
       'abc\\Tdeff/u',
       'abc\\Udeff/u',
       'abc\\Vdeff/u',
       'abc\\Ydeff/u',
       'abc\\Zdeff/u',

       '\\Aabcd/u',
      '\\Cabcd/u',
      '\\Eabcd/u',
      '\\Fabcd/u',
      '\\Gabcd/u',
      '\\Habcd/u',
      '\\Iabcd/u',
      '\\Jabcd/u',
      '\\Kabcd/u',
      '\\Labcd/u',
      '\\Mabcd/u',
      '\\Nabcd/u',
      '\\Oabcd/u',
      '\\Pabcd/u',
      '\\Qabcd/u',
      '\\Rabcd/u',
      '\\Tabcd/u',
      '\\Uabcd/u',
      '\\Vabcd/u',
      '\\Yabcd/u',
      '\\Zabcd/u',

       '\\aabcd/u',
      '\\eabcd/u',
      '\\gabcd/u',
      '\\habcd/u',
      '\\iabcd/u',
      '\\jabcd/u',
      '\\kabcd/u',
      '\\labcd/u',
      '\\mabcd/u',
      '\\oabcd/u',
      '\\pabcd/u',
      '\\qabcd/u',
      '\\yabcd/u',
      '\\zabcd/u',

       '\\A/u',
       '\\E/u',
       '\\F/u',
       '\\G/u',
       '\\H/u',
       '\\I/u',
       '\\J/u',
       '\\K/u',
       '\\L/u',
       '\\M/u',
       '\\N/u',
       '\\O/u',
       '\\P/u',
       '\\Q/u',
       '\\R/u',
       '\\T/u',
       '\\U/u',
       '\\V/u',
       '\\X/u',
       '\\Y/u',
       '\\Z/u',
       //`a{01,1}/u`,
       //`a{1,02}/u`,
       //`a{03,04}/u`,
       //`a{00,00}/u`




      //`a{11,0}/u`,
//      `a{12,1}/u`,
  //    `a{23,2}/u`,
    //  `a{34,3}/u`,
      //`a{45,4}/u`,
      //`a{56,5}/u`,
      //`a{67,6}/u`,
      //`a{78,7}/u`,
      //`a{89,8}/u`,
      //`a{90,9}/u`
    ];

    for (const arg of InValidUnicodeCases) {
      fail(`Fail ${arg}`, {
       name: `${arg}`,
       source: `${arg}`,
       value: 'foo',
       raw: 'foo',
       context: Context.OptionsAnnexB,
       token: Token.Identifier,
       line: 1,
       column: 3,
   });
   }

   const ValidUnicodeCases = [

    '[\\ca]/u',
    '[\\cb]/u',
    '[\\cd]/u',
    '[\\ce]/u',
    '[\\cf]/u',
    '[\\cg]/u',
    '[\\ch]/u',
    '[\\ci]/u',
    '[\\cj]/u',
    '[\\ck]/u',
    '[\\cl]/u',
    '[\\cm]/u',
    '[\\cn]/u',
    '[\\co]/u',
    '[\\cp]/u',
    '[\\cq]/u',
    '[\\cr]/u',
    '[\\cs]/u',
    '[\\ct]/u',
    '[\\cu]/u',
    '[\\cv]/u',
    '[\\cw]/u',
    '[\\cx]/u',
    '[\\cy]/u',
    '[\\cz]/u',

    '[\\fabcd]/u',
    '[\\dabcd]/u',
    '[\\Dabcd]/u',
    '[\\nabcd]/u',
    '[\\rabcd]/u',
    '[\\sabcd]/u',
    '[\\Sabcd]/u',
    '[\\tabcd]/u',
    '[\\vabcd]/u',
    '[\\wabcd]/u',
    '[\\Wabcd]/u',

    '[abc\\d]/u',
    '[abc\\D]/u',
    '[abc\\f]/u',
    '[abc\\n]/u',
    '[abc\\r]/u',
    '[abc\\s]/u',
    '[abc\\S]/u',
    '[abc\\t]/u',
    '[abc\\v]/u',
    '[abc\\w]/u',
    '[abc\\W]/u',

    '[\\d]/u',
    '[\\D]/u',
    '[\\f]/u',
    '[\\n]/u',
    '[\\r]/u',
    '[\\s]/u',
    '[\\S]/u',
    '[\\t]/u',
    '[\\v]/u',
    '[\\w]/u',
    '[\\W]/u',

    '[^-J]/ug',
    '[^-fdsasgJ]/gu',
    '[^J-]/ug',
    '[^Jdsads-]/ug',
    '[^--]/ug',
    '[^---]/ug',

    `[\\b]/u`,
    `[a\\bc]/u`,
    `[\\bc]/u`,
    `[a\\bb]/u`,
    `[\\-]/u`,
    `[a\\-c]/u`,
    `[\\-c]/u`,
    `[a\\-b]/u`,

    `[rD]/u`,
    `[Kq]/u`,
    `[$%]/u`,

    `[A]/u`,
    `[B]/u`,
    `[C]/u`,
    `[D]/u`,
    `[E]/u`,
    `[F]/u`,
    `[G]/u`,
    `[H]/u`,
    `[I]/u`,
    `[J]/u`,
    `[K]/u`,
    `[L]/u`,
    `[M]/u`,
    `[N]/u`,
    `[O]/u`,
    `[P]/u`,
    `[Q]/u`,
    `[R]/u`,
    `[S]/u`,
    `[T]/u`,
    `[U]/u`,
    `[V]/u`,
    `[W]/u`,
    `[X]/u`,
    `[Y]/u`,
    `[Z]/u`,

    `[a]/u`,
    `[b]/u`,
    `[c]/u`,
    `/[d]/u`,
    `[e]/u`,
    `[f]/u`,
    `[g]/u`,
    `[h]/u`,
    `[i]/u`,
    `[j]/u`,
    `[k]/u`,
    `[l]/u`,
    `[m]/u`,
    `[n]/u`,
    `[o]/u`,
    `[p]/u`,
    `[q]/u`,
    `[r]/u`,
    `[s]/u`,
    `[t]/u`,
    `[u]/u`,
    `[v]/u`,
    `[w]/u`,
    `[x]/u`,
    `[y]/u`,
    `[z]/u`,

    `[^]/u`,
    `a[^]/u`,
    `[^]b/u`,
    `a[^]b/u`,
    `[]/u`,
    `a[]/u`,
    `[]b/u`,
    `a[]b/u`,

    '\\0/u',
    '(a)\\0/u',
    //'(((((((((((((((((((((a)))))))))))))))))))))\\20/u',

    '\\1(a)/u',
    '(a)\\1/u', '(\\1)/u',

    '\\1x(a)/u',
    '(a)x\\1/u',
    '(a\\1b)/u',
    '0\\1(a)/u',
    '4\\1(a)/u',
    '(a)|\\1/u',
    '\\1|(a)/u',
    '(\\1|a)/u',
    '(a|\\1)/u',

    'a||/u',
    'a|(|)/u',
    'a|(|)/u',
    '/|/u',

    '^/u',
    '$/u',
    './u',

    //`\\^def/u`,
    //`\\$def/u`,
    //`\\\\def/u`,
    //`\\.def/u`,
    //`\\*def/u`,
    //`\\+def/u`,
    //`\\?def/u`,
    //`\\(def/u`,
    //`\\)def/u`,
    //`\\[def/u`,
    //`\\]def/u`,
    //`\\{def/u`,
    //`\\}def/u`,
    //`\\|def/u`,

    //`abc\\^/u`,
    //`abc\\$/u`,
    //`abc\\\\/u`,
    //`abc\\./u`,
    //`abc\\*/u`,
    //`abc\\+/u`,
    //`abc\\?/u`,
    //`abc\\(/u`,
    //`abc\\)/u`,
    //`abc\\[/u`,
    //`abc\\]/u`,
    //`abc\\{/u`,
    //`abc\\}/u`,
    //`abc\\|/u`,

    '\\fabcd/u',
    '\\dabcd/u',
    '\\Dabcd/u',
    '\\nabcd/u',
    '\\rabcd/u',
    '\\sabcd/u',
    '\\Sabcd/u',
    '\\tabcd/u',
    '\\vabcd/u',
    '\\wabcd/u',
    '\\Wabcd/u',

    `a{11,15}/u`, `a{12,26}/u`, `a{23,37}/u`,

    `a{0}/u`, `a{1}/u`, `a{2}/u`, `a{3}/u`, `a{4}/u`, `a{5}/u`, `a{6}/u`, `a{7}/u`, `a{8}/u`, `a{9}/u`,
    `a{11}/u`, `a{12}/u`, `a{23}/u`, `a{34}/u`, `a{45}/u`, `a{56}/u`, `a{67}/u`, `a{78}/u`, `a{89}/u`, `a{90}/u`,
    `a{0,}/u`, `a{1,}/u`, `a{2,}/u`, `a{3,}/u`, `a{4,}/u`, `a{5,}/u`, `a{6,}/u`, `a{7,}/u`, `a{8,}/u`, `a{9,}/u`,
    `a{11,}/u`, `a{12,}/u`, `a{23,}/u`, `a{34,}/u`, `a{45,}/u`, `a{56,}/u`, `a{67,}/u`, `a{78,}/u`, `a{89,}/u`, `a{90,}/u`,

    `^abc/u`, `abc$/u`, `a.c/u`,
    `|a/u`, `a|/u`, `|/u`, 'a||/u',

    `a{34,48}/u`, `a{45,59}/u`, `a{56,60}/u`, `a{67,71}/u`, `a{78,82}/u`, `a{89,93}/u`, `a{90,94}/u`,

    'abc\\d/u', 'abc\\D/u', 'abc\\f/u', 'abc\\n/u', 'abc\\r/u', 'abc\\s/u', 'abc\\S/u', 'abc\\t/u',

    'abc\\fdeff/u',
    'abc\\ddeff/u',
    'abc\\Ddeff/u',
    'abc\\ndeff/u',
    'abc\\rdeff/u',
    'abc\\sdeff/u',
    'abc\\Sdeff/u',
    'abc\\tdeff/u',
    'abc\\vdeff/u',
    'abc\\wdeff/u',
    'abc\\Wdeff/u',

    '\\ca/u',
    '\\cb/u',
    '\\cd/u',
    '\\ce/u',
    '\\cf/u',
    '\\cg/u',
    '\\ch/u',
    '\\ci/u',
    '\\cj/u',
    '\\ck/u',
    '\\cl/u',
    '\\cm/u',
    '\\cn/u',
    '\\co/u',
    '\\cp/u',
    '\\cq/u',
    '\\cr/u',
    '\\cs/u',
    '\\ct/u',
    '\\cu/u',
    '\\cv/u',
    '\\cw/u',
    '\\cx/u',
    '\\cy/u',
    '\\cz/u',

    '\\cA/u',
    '\\cB/u',
    '\\cD/u',
    '\\cE/u',
    '\\cF/u',
    '\\cG/u',
    '\\cH/u',
    '\\cI/u',
    '\\cJ/u',
    '\\cK/u',
    '\\cL/u',
    '\\cM/u',
    '\\cN/u',
    '\\cO/u',
    '\\cP/u',
    '\\cQ/u',
    '\\cR/u',

    '\\cS/u',
    '\\cT/u',
    '\\cU/u',
    '\\cV/u',
    '\\cW/u',
    '\\cX/u',
    '\\cY/u',
    '\\cZ/u',

    '\\0/u', 'a\\0/u', '\\0b/u', 'a\\0b/u', '(a)\\0/u', '\\0(b)/u', '(\\0)/u', '(0\\0)/u', '(1\\0)/u',
    // '\\x01/u', '\\x12/u', '\\x23/u', '\\x34/u', '\\x45/u', '\\x56/u', '\\x67/u', '\\x78/u', '\\x89/u', '\\x90/u',
    //'\\xa1/u',

    //'\\ud800/u',

    // `\\u{0000000000000000000010ffff}/u`,
    // `\\u{10ffff}/u`,
    //`prefix \\u{012345}/u`,

    // '\\ud800\\udc00\\ud800/u',
    // 'x\\ud810\\udc10\\ud810/u',
    // '\\ud900\\udd00\\ud900y/u',
    // 'x\\udabc\\udebc\\udabcy/u',

    //`\\u{0123}/u`,

    //'[\\0]/u',
    //'[a\\0]/u',
    //'[\\0b]/u',
    //'[a\\0b]/u',
    //'[0\\0b]/u',
    //'[1\\0b]/u',

    '[abc\\fdeff]/u',
    '[abc\\ddeff]/u',
    '[abc\\Ddeff]/u',
    '[abc\\ndeff]/u',
    '[abc\\rdeff]/u',
    '[abc\\sdeff]/u',
    '[abc\\Sdeff]/u',
    '[abc\\tdeff]/u',
    '[abc\\vdeff]/u',
    '[abc\\wdeff]/u',
    '[abc\\Wdeff]/u',

    '[\\$]/u',
    '[abc\\$]/u',
    '[\\$abcd]/u',
    '[abc\\$abcd]/u',

    `[\\^]/u`,
    `[\\$]/u`,
    `[\\\\]/u`,
    `[\\.]/u`,
    `[\\*]/u`,
    `[\\+]/u`,
    `[\\?]/u`,
    `[\\(]/u`,
    `[\\)]/u`,
    `[\\[]/u`,
    `[\\]]/u`,
    `[\\{]/u`,
    `[\\}]/u`,
    `[\\|]/u`,

    `[abc\\^]/u`,
    `[abc\\$]/u`,
    `[abc\\\\]/u`,
    `[abc\\.]/u`,
    `[abc\\*]/u`,
    `[abc\\+]/u`,
    `[abc\\?]/u`,
    `[abc\\(]/u`,
    `[abc\\)]/u`,
    `[abc\\[]/u`,
    `[abc\\]]/u`,
    `[abc\\{]/u`,
    `[abc\\}]/u`,
    `[abc\\|]/u`,

    `[\\^def]/u`,
    `[\\$def]/u`,
    `[\\\\def]/u`,
    `[\\.def]/u`,
    `[\\*def]/u`,
    `[\\+def]/u`,
    `[\\?def]/u`,
    `[\\(def]/u`,
    `[\\)def]/u`,
    `[\\[def]/u`,
    `[\\]def]/u`,
    `[\\{def]/u`,
    `[\\}def]/u`,
    `[\\|def]/u`,

    '[\\cA]/u',
    '[\\cB]/u',
    '[\\cD]/u',
    '[\\cE]/u',
    '[\\cF]/u',
    '[\\cG]/u',
    '[\\cH]/u',
    '[\\cI]/u',
    '[\\cJ]/u',
    '[\\cK]/u',
    '[\\cL]/u',
    '[\\cM]/u',
    '[\\cN]/u',
    '[\\cO]/u',
    '[\\cP]/u',
    '[\\cQ]/u',
    '[\\cR]/u',
    '[\\cS]/u',
    '[\\cT]/u',
    '[\\cU]/u',
    '[\\cV]/u',
    '[\\cW]/u',
    '[\\cX]/u',
    '[\\cY]/u',
    '[\\cZ]/u',

       '[\\ud800\\ud800]/u',
       '[x\\ud810\\ud810]/u',
       '[\\ud900\\ud900y]/u',
       '[x\\udabc\\udabcy]/u',

      '[\\udc00]/u',
      '[x\\udc10]/u',
      '[\\udd00y]/u',
      '[x\\udebcy]/u',
      '[x\\udebcy]/gu',
      '[x\\udebcy]/imu',
      '[x\\udebcy]/uy',

      '[\\xa1]/u',
      '[\\xb2]/u',
      '[\\xc3]/u',
      '[\\x3d]/u',
      '[\\x4e]/u',
      '[\\x5f]/u',
      '[\\x6A]/u',
      '[\\xbB]/u',
      '[\\xCD]/u',
      '[\\xEF]/u',

      '[\\ud800\\udc00]/u',
      '[x\\ud810\\udc10]/u',
      '[\\ud900\\udd00y]/u',
      '[x\\udabc\\udebcy]/u',
      '[x\\udabc\\udebcy]/ug',

      '[\\u5000-\\u6000]/u',
      '[\\uD83D\\uDCA9]/u',
       '[\\uD83D\\uDCAB]/u',
       '[\\uD83D\\uDCA9-\\uD83D\\uDCAB]/u',
      '[\uD83D\\uDCA9-\\uD83D\\uDCAB]/u',
      '[\\uD83D\uDCA9-\\uD83D\\uDCAB]/u',
      '[\\uD83D\\uDCA9-\uD83D\\uDCAB]/u',
      '[\\uD83D\\uDCA9-\\uD83D\uDCAB]/u',
      '[\uD83D\uDCA9-\\uD83D\\uDCAB]/u',
      '[\uD83D\\uDCA9-\uD83D\\uDCAB]/u',
      '[\uD83D\\uDCA9-\\uD83D\uDCAB]/u',
      '[\\uD83D\uDCA9-\uD83D\\uDCAB]/u',
      '[\\uD83D\uDCA9-\\uD83D\uDCAB]/u',
      '[\\uD83D\\uDCA9-\uD83D\uDCAB]/u',
      '[\uD83D\uDCA9-\uD83D\\uDCAB]/u',
      '[\uD83D\uDCA9-\\uD83D\uDCAB]/u',
      '[\\uD83D\uDCA9-\uD83D\uDCAB]/u',
      '[\uD83D\uDCA9-\uD83D\uDCAB]/u',
      '[1-\\u{500}]/u',
      //'\\u{01}-\\x07/u',
      '[\\u{5}-1]/u',
      '[\\x01-\\u{347}]/u',
       '[\\x01-\\x17]/u',
        '[\\u0001-\\x17]/u',
      '[\\x01-\\u0007]/u',
       '[\\x01-\\x17]/u',
      '[A-\\cH]/u',
      '[\\cH-Z]/u',
      '(a(b))/u',
      'a(a(b))/u',
      '(a(b))c/u',
      'a(a(b))c/u',
      '((b)c)/u',
      'a((b)c)/u',
      '((b)c)c/u',
      'a((b)c)c/u',
      '(a(b)c)/u',
      'a(a(b)c)/u',
      '(a(b)c)c/u',
      'a(a(b)c)c/u',
      '(?:(?:b))/u',
      '(?:a(?:b))/u',
      'a(?:a(?:b))/u',
      '(?:a(?:b))c/u',
      'a(?:a(?:b))c/u',
      '(?:(?:b)c)/u',
      'a(?:(?:b)c)/u',
      '(?:(?:b)c)c/u',
      'a(?:(?:b)c)c/u',
      '(?:a(?:b)c)/u',
      'a(?:a(?:b)c)/u',
      '(?:a(?:b)c)c/u',
      'a(?:a(?:b)c)c/u',

      '[\\udc00\\udc00]/u',
      '[x\\udc10\\udc10]/u',
      '[\\udd00\\udd00y]/u',
      '[x\\udebc\\udebcy]/u',
      '[x\\udebc\\udebcy]/ui'
  ];

  for (const arg of ValidUnicodeCases) {
    pass(`Pass ${arg}`, {
     name: `${arg}`,
     source: `${arg}`,
     value: 'foo',
     raw: 'foo',
     context: Context.OptionsAnnexB,
     token: Token.Identifier,
     line: 1,
     column: 3,
 });
  }


  });



  describe('Non-Unicode', () => {

    const InValidNonUnicodeCases = [
      "\\p/u",
      "[\\p{Script=Hiragana}-\\p{Script=Katakana}]/u",
      // "\\p{General_Category=Hiragana}/u",
      "(?=/",
      "(a{2,1}/",
      "$*/",
      "\\2(a)(/",
      "(?:a/",
      // "[a-b--+]/",
      "[\\u{1}-\\u{2}]/",
      "[\\u{2}-\\u{1}]/",
      // "[\\c-a]/",
      "[🌷-🌸]/",
      "[\\uD834\\uDF06-\\uD834\\uDF08a-z]/",
      "\\\r/",
      //"/*",
      "(?<=a)?/",
      "(?<=a)?/u",
      "(?<=a)*/",
      "(?<=a){1}/",
      "(?<!a)?/",
      "(?<!a)?/u",
      "(?<!a){1}/",
      "(?<!a){1}/u",
      "[\\u{2}-\\u{1}]/",
      "(?a/",
      "(?<a>a)\\k</",
      "(?<a>a)\\k</u",
      "(?<a>a)\\k</u",
      "(?<a>a)\\2/u",
      //"/(?<\\u0020>a)\\k<\\u0020>/u",
      // "/(?<11>a)\\k<11>/u",
      "(?<!a)+/",
      "(?<!a)?/",
      "(/",
      `|a`, `a|`, `|`, 'a||',
      `^`, `abc$`, `a.`,
      `a*`, `a?`, `a+`,
      `a*?`, `a?*`, `a+?`,
      `?/`,
      `+/`,
      `?a/`,
      `+a/`,
      `??/`,
      `+?/`,
      `|*/`,
      `|?/`,
      `|+/`,
      `*/`,
      `*`,
      `*a/`,
      `*a`,
      `a**/`,
      `a?+/`,
      `a++/`,
      `a**`,
      `a?*`,
      `a++`,

      // 'a{1, 1}/', 'a{ 1, 1}/', 'a{1 ,1}/',

      `a??`,

      //`a{0x01,1}/`,
      //`a{0x15,02}/`,
      //`a{0b01,04}/`,
      // `a{00,0o01}/`,
      'foo/gmmi', 'foo/ggymi', 'foo/myiy', 'foo/igyi',

      // `a{1,0}/`,
   //    `a{2,1}/`,
//       `a{100,45}/`,

      // `a{01,1}/`,
      // `a{1,02}/`,
      // `a{03,04}/`,
      // `a{00,00}/`,

      // `a{11,0}/`,
      // `a{12,1}/`,
      // `a{23,2}/`,
      // `a{34,3}/`,
      // `a{45,4}/`,
      // `a{56,5}/`,
      // `a{67,6}/`,
      // `a{78,7}/`,
      // `a{89,8}/`,
      // `a{90,9}/`,

      // `\\u{10ffff}/`,
      `/\\u{110000}/`,
      `/\\u{0000000000000000000010ffff}/`,
      `/\\u{00000000000000000000110000}/`,

      '\\1(a)',
      '(a)\\1',
      '(\\1)',
//      'a\\1/',

'x\\u', 'x\\u0', 'x\\uf8', 'x\\ubcd', 'x\\ubcde',
'\\u', '\\u0', '\\uf8', '\\ubcd', '\\ubcde',
  //    '(\\12|a)/',
//      '(a|\\13)/',
//`\\u{0123}/`,
//`\\u{}/`,
      // 'a\\1/',
      '\\0',
      '\\0', 'a\\0', '\\0b', 'a\\0b', '(a)\\0', '\\0(b)', '(\\0)',
      '\\01', 'a\\02', '\\03b', 'a\\04b', '(a)\\05', '\\06(b)', '(\\07)', '\\08', '\\09', '\\00',
      '\\1(a)',
      '(a)\\1',
      '(\\1)',
      '\\1x(a)',
      '(a)x\\1',
      '(a\\1b)',
      '0\\1(a)',
      '4\\1(a)',
      '(a)|\\1',
      '\\1|(a)',
      '(\\1|a)',
      '(a|\\1)',
      '\\a',
      '\\b',
      '\\d',
      '\\e',
      '\\f',
      '\\g',
      '\\h',
      '\\i',
      '\\j',
      '\\k',
      '\\l',
      '\\m',
      '\\n',
      '\\o',
      '\\p',
      '\\q',
      '\\r',
      '\\s',
      '\\t',
      '\\u',
      '\\v',
      '\\w',
      '\\x',
      '\\y',
      '\\z',

      '\\ca',
      '\\cb',
      '\\cc',
      '\\cd',
      '\\ce',
      '\\cf',
      '\\cg',
      '\ch',
      '/\\ci',
      '\\cj',
      '\\ck',
      '\\cl',
      '\\cm',
      '\\cn',
      '\\co',
      '\\cp',
      '\\cq',
      '\\cr',
      '\\cs',
      '\\ct',
      '\\cu',
      '\\cv',
      '\\cw',
      '\\cx',
      '\\cy',
      '\\cz',

      '\\cA',
      '\\cB',
      '\\cC',
      '\\cD',
      '\\cE',
      '\\cF',
      '\\cG',
      '\\cH',
      '\\cI',
      '\\cJ',
      '\\cK',
      '\\cL',
      '\\cM',
      '\\cN',
      '\\cO',
      '\\cP',
      '\\cQ',
      '\\cR',
      '\\cS',
      '\\cT',
      '\\cU',
      '\\cV',
      '\\cW',
      '\\cX',
      '\\cY',
      '\\cZ',
      'abc\\A',
      'abc\\B',
      'abc\\D',
      'abc\\E',
      'abc\\F',
      'abc\\G',
      'abc\\H',
      'abc\\I',
      'abc\\J',
      'abc\\K',
      'abc\\L',
      'abc\\M',
      'abc\\N',
      'abc\\O',
      'abc\\P',
      'abc\\Q',
      'abc\\R',
      'abc\\S',
      'abc\\T',
      'abc\\U',
      'abc\\V',
      'abc\\W',
      'abc\\X',
      'abc\\Y',
      'abc\\Z',
      'abc\\Adeff',
      'abc\\Bdeff',
      'abc\\Cdeff',
      'abc\\Ddeff',
      'abc\\Edeff',
      'abc\\Fdeff',
      'abc\\Gdeff',
      'abc\\Hdeff',
      'abc\\Ideff',
      'abc\\Jdeff',
      'abc\\Kdeff',
      'abc\\Ldeff',
      'abc\\Mdeff',
      'abc\\Ndeff',
      'abc\\Odeff',
      'abc\\Pdeff',
      'abc\\Qdeff',
      'abc\\Rdeff',
      'abc\\Sdeff',
      'abc\\Tdeff',
      'abc\\Udeff',
      'abc\\Vdeff',
      'abc\\Wdeff',
      'abc\\Xdeff',
      'abc\\Ydeff',
      'abc\\Zdeff',
      'abc\\adeff',
      'abc\\bdeff',
      'abc\\cdeff',
      'abc\\ddeff',
      'abc\\edeff',
      'abc\\fdeff',
      'abc\\gdeff',
      'abc\\hdeff',
      'abc\\ideff',
      'abc\\jdeff',
      'abc\\kdeff',
      'abc\\ldeff',
      'abc\\mdeff',
      'abc\\ndeff',
      'abc\\odeff',
      'abc\\pdeff',
      'abc\\qdeff',
      'abc\\rdeff',
      'abc\\sdeff',
      'abc\\tdeff',
      'abc\\udeff',
      'abc\\vdeff',
      'abc\\wdeff',
      'abc\\xdeff',
      'abc\\ydeff',
      'abc\\zdeff',
      '\\Aabcd',
      '\\Babcd',
      '\\Cabcd',
      '\\Dabcd',
      '\\Eabcd',
      '\\Fabcd',
      '\\Gabcd',
      '\\Habcd',
      '\\Iabcd',
      '\\Jabcd',
      '\\Kabcd',
      '\\Labcd',
      '\\Mabcd',
      '\\Nabcd',
      '\\Oabcd',
      '\\Pabcd',
      '\\Qabcd',
      '\\Rabcd',
      '\\Sabcd',
      '\\Tabcd',
      '\\Uabcd',
      '\\Vabcd',
      '\\Wabcd',
      '\\Xabcd',
      '\\Yabcd',
      '\\Zabcd',
      '\\aabcd',
      '\\babcd',
      '\\cabcd',
      '\\dabcd',
      '\\eabcd',
      '\\fabcd',
      '\\gabcd',
      '\\habcd',
      '\\iabcd',
      '\\jabcd',
      '\\kabcd',
      '\\labcd',
      '\\mabcd',
      '\\nabcd',
      '\\oabcd',
      '\\pabcd',
      '\\qabcd',
      '\\rabcd',
      '\\sabcd',
      '\\tabcd',
      '\\uabcd',
      '\\vabcd',
      '\\wabcd',
      '\\xabcd',
      '\\yabcd',
      '\\zabcd',

      //'abc\\adeff/',

      // 'abc\\gdeff/',
      // 'abc\\hdeff/',
      // 'abc\\ideff/',
      // 'abc\\jdeff/',
      // 'abc\\kdeff/',
      // 'abc\\ldeff/',
      // 'abc\\mdeff/',
      // 'abc\\odeff/',
      // 'abc\\pdeff/',
      // 'abc\\qdeff/',
      // 'abc\\ydeff/',
      // 'abc\\zdeff/',

      // 'abc\\Adeff/',
      // 'abc\\Cdeff/',
      // 'abc\\Edeff/',
      // 'abc\\Fdeff/',

      // 'abc\\Tdeff/',
      // 'abc\\Udeff/',
      // 'abc\\Vdeff/',
      // 'abc\\Ydeff/',
      // 'abc\\Zdeff/',
       'a|*/',
       'a|+/',
       'a|?/',
      'a|)/',
      // 'a|]/',
      // 'a|{/',
      // 'a|}/',
      '\\_/',
      'abc\\_/',
      //'\\_abcd/',
      //'abc\\_abcd/',

      // '\\aabcd/',

      '\\/', 'a|\\/',

      'abc\\a/',
      'abc\\e/',

      'abc\\g/',
      'abc\\h/',
      'abc\\i/',
      'abc\\j/',
      'abc\\l/',
      'abc\\m/',
      'abc\\o/',
      // 'abc\\p/',
      'abc\\q/',
      // 'abc\\u/',
      // 'abc\\x/',
      'abc\\y/',
      'abc\\z/',

      'abc\\A/',
      'abc\\E/',
      'abc\\F/',
      'abc\\G/',
      'abc\\H/',
      'abc\\I/',
      'abc\\J/',
      'abc\\K/',
      'abc\\L/',
      'abc\\M/',
      'abc\\N/',
      'abc\\O/',
      // 'abc\\P/',
      'abc\\Q/',
      'abc\\R/',
      'abc\\T/',
      'abc\\U/',
      'abc\\V/',
      'abc\\X/',
      'abc\\Y/',
      'abc\\Z/',

      '\\a/',
      '\\e/',
      '\\g/',

      '\\h/',
      '\\i/',
      '\\j/',
      '\\l/',
      '\\m/',
      '\\o/',
      // '\\p/',
      '\\q/',
      // '\\u/',
      // '\\x/',
      '\\y/',
      '\\z/',

      '\\A/',
      '\\E/',
      '\\F/',
      '\\G/',
      '\\H/',
      '\\I/',
      '\\J/',
      '\\K/',
      '\\L/',
      '\\M/',
      '\\N/',
      '\\O/',
      // '\\P/',
      '\\Q/',
      '\\R/',
      '\\T/',
      '\\U/',
      '\\V/',
      '\\X/',
      '\\Y/',
      '\\Z/',

      //'\\Zabcd/',

      //'abc\\Adeff/',
      //'abc\\Cdeff/',

      //'\\2(a)/',
      //'(a)\\3/',
      //'(\\4)/',
      //'\\5x(a)/',
      //'(a)x\\6/',
      //'(a\\7b)/',
      //'0\\8(a)/',
      //'4\\9(a)/',
      //'(a)|\\10/',
      //'\\11|(a)/',
      //'(\\12|a)/',
      //'(a|\\13)/'

      //'\\Aabcd/',
      //'\\Cabcd/',
      //'\\Eabcd/',

      // '\\Fabcd/',
      // '\\Gabcd/',
      // '\\Habcd/',
      // '\\Iabcd/',
      // '\\Jabcd/',
      // '\\Kabcd/',
      // '\\Labcd/',
      // '\\Mabcd/',
      // '\\Nabcd/',
      // '\\Oabcd/',
      // '\\Pabcd/',
      // '\\Qabcd/',
      // '\\Rabcd/',
      // '\\Tabcd/',
      // '\\Uabcd/',
      // '\\Vabcd/',
      // '\\Yabcd/',
      // '\\Zabcd/',


      // '\\k/',
      //'abc\\k/',

      // `[\\-]/`,
      // `[a\\-c]/`,
      // `[\\-c]/`,
      // `[a\\-b]/`,

      // '[\\1]/',
      // '[\\2]/',
      // '[\\3]/',
      // '[\\4]/',
      // '[\\5]/',
      // '[\\6]/',
      // '[\\7]/',
      // '[\\8]/',
      // '[\\9]/'

      //'[\\00]/',
      //'[\\01]/',
      //'[\\02]/',
      //'[\\03]/',
      //'[\\04]/',
      //'[\\05]/',
      //'[\\06]/',
      //'[\\07]/',
      //'[\\08]/',
      //'[\\09]/'

      //'[\\90]/',
      //'[\\12]/',
      //'[\\23]/',
      //'[\\34]/',
      //'[\\45]/',
      //'[\\56]/',
      //'[\\67]/',
      //'[\\78]/',
      //'[\\89]/',
      //'[\\91]/'
      '[\\0',
      '[\\1',
      '[\\2',
      '[\\3',
      '[\\4',
      '[\\5',
      '[\\6',
      '[\\7',
      '[\\8',
      '[\\9',

      '[\\a]/',
      '[\\e]/',
      '[\\g]/',
      '[\\h]/',
      '[\\i]/',
      '[\\j]/',
      '[\\k]/',
      '[\\l]/',
      '[\\m]/',
      '[\\o]/',
      // '[\\p]/',
      '[\\q]/',
      '[\\u]/',
      '[\\x]/',
      '[\\y]/',
      '[\\z]/',

      '[\\A]/',
      '[\\E]/',
      '[\\F]/',
      '[\\G]/',
      '[\\H]/',
      '[\\I]/',
      '[\\J]/',
      '[\\K]/',
      '[\\L]/',
      '[\\M]/',
      '[\\N]/',
      '[\\O]/',
      // '[\\P]/',
      '[\\Q]/',
      '[\\R]/',
      '[\\T]/',
      '[\\U]/',
      '[\\V]/',
      '[\\X]/',
      '[\\Y]/',
      '[\\Z]/',

      '[abc\\a]/',
      '[abc\\e]/',
      '[abc\\g]/',
      '[abc\\h]/',
      '[abc\\i]/',
      '[abc\\j]/',
      '[abc\\k]/',
      '[abc\\l]/',
      '[abc\\m]/',
      '[abc\\o]/',
      // '[abc\\p]/',
      '[abc\\q]/',
      '[abc\\u]/',
      '[abc\\x]/',
      '[abc\\y]/',
      '[abc\\z]/',

      '[abc\\A]/',
      '[abc\\E]/',
      '[abc\\F]/',
      '[abc\\G]/',
      '[abc\\H]/',
      '[abc\\I]/',
      '[abc\\J]/',
      '[abc\\K]/',
      '[abc\\L]/',
      '[abc\\M]/',
      '[abc\\N]/',
      '[abc\\O]/',
      // '[abc\\P]/',
      '[abc\\Q]/',
      '[abc\\R]/',
      '[abc\\T]/',
      '[abc\\U]/',
      '[abc\\V]/',
      '[abc\\X]/',
      '[abc\\Y]/',
      '[abc\\Z]/',

      '[\\aabcd]/',
      '[\\eabcd]/',
      '[\\gabcd]/',
      '[\\habcd]/',
      '[\\iabcd]/',
      '[\\jabcd]/',
      '[\\kabcd]/',
      '[\\labcd]/',
      '[\\mabcd]/',
      '[\\oabcd]/',
      // '[\\pabcd]/',
      '[\\qabcd]/',
      '[\\yabcd]/',
      '[\\zabcd]/',

      '[\\Aabcd]/',
      '[\\Cabcd]/',
      '[\\Eabcd]/',
      '[\\Fabcd]/',
      '[\\Gabcd]/',
      '[\\Habcd]/',
      '[\\Iabcd]/',
      '[\\Jabcd]/',
      '[\\Kabcd]/',
      '[\\Labcd]/',
      '[\\Mabcd]/',
      '[\\Nabcd]/',
      '[\\Oabcd]/',
      // '[\\Pabcd]/',
      '[\\Qabcd]/',
      '[\\Rabcd]/',
      '[\\Tabcd]/',
      '[\\Uabcd]/',
      '[\\Vabcd]/',
      '[\\Xabcd]/',
      '[\\Yabcd]/',
      '[\\Zabcd]/',

      '[abc\\adeff]/',
      '[abc\\gdeff]/',
      '[abc\\hdeff]/',
      '[abc\\ideff]/',
      '[abc\\jdeff]/',
      '[abc\\kdeff]/',
      '[abc\\ldeff]/',
      '[abc\\mdeff]/',
      '[abc\\odeff]/',
      // '[abc\\pdeff]/',
      '[abc\\qdeff]/',
      '[abc\\ydeff]/',
      '[abc\\zdeff]/',

      '[abc\\Adeff]/',
      '[abc\\Cdeff]/',
      '[abc\\Edeff]/',
      '[abc\\Fdeff]/',
      '[abc\\Gdeff]/',
      '[abc\\Hdeff]/',
      '[abc\\Ideff]/',
      '[abc\\Jdeff]/',
      '[abc\\Kdeff]/',
      '[abc\\Ldeff]/',
      '[abc\\Mdeff]/',
      '[abc\\Ndeff]/',
      '[abc\\Odeff]/',
      // '[abc\\Pdeff]/',
      '[abc\\Qdeff]/',
      '[abc\\Rdeff]/',
      '[abc\\Tdeff]/',
      '[abc\\Udeff]/',
      '[abc\\Vdeff]/',
      '[abc\\Xdeff]/',
      '[abc\\Ydeff]/',
      '[abc\\Zdeff]/',

      '[\\ca',
      '[\\cb',
      '[\\cc',
      '[\\cd',
      '[\\ce',
      '[\\cf',
      '[\\cg',
      '[\\ch',
      '[\\ci',
      '[\\cj',
      '[\\ck',
      '[\\cl',
      '[\\cm',
      '[\\cn',
      '[\\co',
      '[\\cp',
      '[\\cq',
      '[\\cr',
      '[\\cs',
      '[\\ct',
      '[\\cu',
      '[\\cv',
      '[\\cw',
      '[\\cx',
      '[\\cy',
      '[\\cz',

      '[\\a',
      '[\\b',
      '[\\d',
      '[\\e',
      '[\\f',
      '[\\g',
      '[\\h',
      '[\\i',
      '[\\j',
      '[\\k',
      '[\\l',
      '[\\m',
      '[\\n',
      '[\\o',
      '[\\p',
      '[\\q',
      '[\\r',
      '[\\s',
      '[\\t',
      '[\\u',
      '[\\v',
      '[\\w',
      '[\\x',
      '[\\y',
      '[\\z',

      '[\\A',
      '[\\B',
      '[\\D',
      '[\\E',
      '[\\F',
      '[\\G',
      '[\\H',
      '[\\I',
      '[\\J',
      '[\\K',
      '[\\L',
      '[\\M',
      '[\\N',
      '[\\O',
      '[\\P',
      '[\\Q',
      '[\\R',
      '[\\S',
      '[\\T',
      '[\\U',
      '[\\V',
      '[\\W',
      '[\\X',
      '[\\Y',
      '[\\Z',

      '[\\$',
      '[abc\\$',
      '[\\$abcd',
      '[abc\\$abcd',
      '[\\_',
      '[abc\\_',
      '[\\_abcd',
      '[abc\\_abcd',

      '[\\x]/',
      '[\\x0]/',
      '[\\x1]/',
      '[\\x2]/',
      '[\\x3]/',
      '[\\x4]/',
      '[\\x5]/',
      '[\\x6]/',
      '[\\x7]/',
      '[\\x8]/',
      '[\\x9]/',

      '[\\x',
      '[\\x0',
      '[\\x1',
      '[\\x2',
      '[\\x3',
      '[\\x4',
      '[\\x5',
      '[\\x6',
      '[\\x7',
      '[\\x8',
      '[\\x9',

      '[\\x01',
      '[\\x12',
      '[\\x23',
      '[\\x34',
      '[\\x45',
      '[\\x56',
      '[\\x67',
      '[\\x78',
      '[\\x89',
      '[\\x90',

      '[\\u',
      '[\\u0',
      '[\\uf8',
      '[\\ubcd',
      '[\\ubcde',



      '[abc\\Adeff',
      '[abc\\Bdeff',
      '[abc\\Cdeff',
      '[abc\\Ddeff',
      '[abc\\Edeff',
      '[abc\\Fdeff',
      '[abc\\Gdeff',
      '[abc\\Hdeff',
      '[abc\\Ideff',
      '[abc\\Jdeff',
      '[abc\\Kdeff',
      '[abc\\Ldeff',
      '[abc\\Mdeff',
      '[abc\\Ndeff',
      '[abc\\Odeff',
      '[abc\\Pdeff',
      '[abc\\Qdeff',
      '[abc\\Rdeff',
      '[abc\\Sdeff',
      '[abc\\Tdeff',
      '[abc\\Udeff',
      '[abc\\Vdeff',
      '[abc\\Wdeff',
      '[abc\\Xdeff',
      '[abc\\Ydeff',
      '[abc\\Zdeff',

      '[abc\\adeff',
      '[abc\\bdeff',
      '[abc\\cdeff',
      '[abc\\ddeff',
      '[abc\\edeff',
      '[abc\\fdeff',
      '[abc\\gdeff',
      '[abc\\hdeff',
      '[abc\\ideff',
      '[abc\\jdeff',
      '[abc\\kdeff',
      '[abc\\ldeff',
      '[abc\\mdeff',
      '[abc\\ndeff',
      '[abc\\odeff',
      '[abc\\pdeff',
      '[abc\\qdeff',
      '[abc\\rdeff',
      '[abc\\sdeff',
      '[abc\\tdeff',
      '[abc\\udeff',
      '[abc\\vdeff',
      '[abc\\wdeff',
      '[abc\\xdeff',
      '[abc\\ydeff',
      '[abc\\zdeff',

      '[\\Aabcd',
      '[\\Babcd',
      '[\\Cabcd',
      '[\\Dabcd',
      '[\\Eabcd',
      '[\\Fabcd',
      '[\\Gabcd',
      '[\\Habcd',
      '[\\Iabcd',
      '[\\Jabcd',
      '[\\Kabcd',
      '[\\Labcd',
      '[\\Mabcd',
      '[\\Nabcd',
      '[\\Oabcd',
      '[\\Pabcd',
      '[\\Qabcd',
      '[\\Rabcd',
      '[\\Sabcd',
      '[\\Tabcd',
      '[\\Uabcd',
      '[\\Vabcd',
      '[\\Wabcd',
      '[\\Xabcd',
      '[\\Yabcd',
      '[\\Zabcd',

      '[\\aabcd',
      '[\\babcd',
      '[\\cabcd',
      '[\\dabcd',
      '[\\eabcd',
      '[\\fabcd',
      '[\\gabcd',
      '[\\habcd',
      '[\\iabcd',
      '[\\jabcd',
      '[\\kabcd',
      '[\\labcd',
      '[\\mabcd',
      '[\\nabcd',
      '[\\oabcd',
      '[\\pabcd',
      '[\\qabcd',
      '[\\rabcd',
      '[\\sabcd',
      '[\\tabcd',
      '[\\uabcd',
      '[\\vabcd',
      '[\\wabcd',
      '[\\xabcd',
      '[\\yabcd',
      '[\\zabcd',

      '[abc\\A',
      '[abc\\B',
      '[abc\\D',
      '[abc\\E',
      '[abc\\F',
      '[abc\\G',
      '[abc\\H',
      '[abc\\I',
      '[abc\\J',
      '[abc\\K',
      '[abc\\L',
      '[abc\\M',
      '[abc\\N',
      '[abc\\O',
      '[abc\\P',
      '[abc\\Q',
      '[abc\\R',
      '[abc\\S',
      '[abc\\T',
      '[abc\\U',
      '[abc\\V',
      '[abc\\W',
      '[abc\\X',
      '[abc\\Y',
      '[abc\\Z',

      '[abc\\a',
      '[abc\\b',
      '[abc\\d',
      '[abc\\e',
      '[abc\\f',
      '[abc\\g',
      '[abc\\h',
      '[abc\\i',
      '[abc\\j',
      '[abc\\k',
      '[abc\\l',
      '[abc\\m',
      '[abc\\n',
      '[abc\\o',
      '[abc\\p',
      '[abc\\q',
      '[abc\\r',
      '[abc\\s',
      '[abc\\t',
      '[abc\\u',
      '[abc\\v',
      '[abc\\w',
      '[abc\\x',
      '[abc\\y',
      '[abc\\z',

      '[\\cA',
      '[\\cB',
      '[\\cC',
      '[\\cD',
      '[\\cE',
      '[\\cF',
      '[\\cG',
      '[\\cH',
      '[\\cI',
      '[\\cJ',
      '[\\cK',
      '[\\cL',
      '[\\cM',
      '[\\cN',
      '[\\cO',
      '[\\cP',
      '[\\cQ',
      '[\\cR',
      '[\\cS',
      '[\\cT',
      '[\\cU',
      '[\\cV',
      '[\\cW',
      '[\\cX',
      '[\\cY',
      '[\\cZ',

      // '[\\_]/',
      // '[abc\\_]/',
      // '[\\_abcd]/',
      // '[abc\\_abcd]/'

      `[\\^`,
      `[\\$`,
      `[\\\\`,
      `[\\.`,
      `[\\*`,
      `[\\+`,
      `[\\?`,
      `[\\(`,
      `[\\)`,
      `[\\]`,
      `[\\]`,
      `[\\{`,
      `[\\}`,
      `[\\|`,

      `[\\u{0123}]/`, `[\\u{4567}]/`, `[\\u{89abc}]/`, `[\\u{defAB}]/`,
      `[\\u{CDEF}]/`,
      `[prefix \\u{012345}]/`,
      `[\\u{012345} postfix]/`,
      `[\\u{012345}\\u{6789a}]/`,
      `[\\u{}]/`,
      `[\\u{fail}]/`,
      `[\\u{afail}]/`,
      `[\\u{0fail}]/`,
      `[\\u{xxxx}]/`,
      `[\\u{]/`, `[\\u{a]/`, `[\\u{af]/`, `[\\u{012]/`, `[\\u{01234]/`, `[\\u{012345]/`,
      `[\\u{1}]/`,
      `[\\u{12}]/`,
      `[\\u{123}]/`,
      `[\\u{1234}]/`,
      `[\\u{12345}]/`,
      `[\\u{103456}]/`,
      `[\\u{`,
      `[\\u{a`,
      `[\\u{af`,
      `[\\u{123`,
      `[\\u{1234`,
      `[\\u{12345`,
      `[\\u{103456`,
      `[\\u{10ffff}]/`,
      `[\\u{110000}]/`,
      `[\\u{120000}]/`,
      `[\\u{900000}]/`,
      `[\\u{123456789}]/`,
      `[\\u{ffffffffffffffff}]/`,
      `[\\u{10000000000000000}]/`,
      `[\\u{fffffffffffffffffffff}]/`,
      `[\\u{0000000000000000000010ffff}]/`,
      `[\\u{00000000000000000000110000}]/`,
      `[\\u{00000000000000000000120000}]/`,
      `[\\u{0000000000123456789}]/`,
      `[\\u{000000ffffffffffffffff}]/`,

       '[\\uD83D\\uDCA9-\\uD83D\\uDCAB]/',
       '[\uD83D\\uDCA9-\\uD83D\\uDCAB]/',
       '[\\uD83D\uDCA9-\\uD83D\\uDCAB]/',
       '[\\uD83D\\uDCA9-\uD83D\\uDCAB]/',
       '[\\uD83D\\uDCA9-\\uD83D\uDCAB]/',
       '[\uD83D\uDCA9-\\uD83D\\uDCAB]/',
      // '[\uD83D\\uDCA9-\uD83D\\uDCAB]/',
       '[\uD83D\\uDCA9-\\uD83D\uDCAB]/',
       '[\\uD83D\uDCA9-\uD83D\\uDCAB]/',
       '[\\uD83D\uDCA9-\\uD83D\uDCAB]/',
      '[\\uD83D\\uDCA9-\uD83D\uDCAB]/',
      '[\uD83D\uDCA9-\uD83D\\uDCAB]/',
      '[\uD83D\uDCA9-\\uD83D\uDCAB]/',
      '[\\uD83D\uDCA9-\uD83D\uDCAB]/',
      '[\uD83D\uDCA9-\uD83D\uDCAB]/',
      //'[x\\d-z]/',
      //'[x\\D-Z]/',
      //'[x\\s-z]/',
      //'[x\\S-S]/',
     // '[x\\w-z]/',
     // '[x\\W-Z]/',
     // '[a-\\d]/',
     // '[A-\\D]/',
     // '[a-\\s]/',
     // '[A-\\S]/',
     // '[a-\\w]/',
     // '[A-\\W]/'

     // '[a-\\dx]/',
     // '[A-\\Dx]/',
     // '[a-\\sx]/',
     // '[A-\\Sx]/',
     // '[a-\\wx]/',
     // '[A-\\Wx]/'

     // '\\2(x)/',

     // '[9-1]/',

     //'[\\u6000-\\u5000]/',

     '[\\u{5}-1]/',
     '[\\x01-\\u{347}]/',
     '[1-\\u{500}]/',
     // '\\u{01}-\\x07/',

//     '[--+]/',
  //   '[0--]/',
    // '[x---]/',
     //'[0---]/',

     //'[x-\\uD83D\\uDE07--+]/',
     //'[x-\\uD83D\\uDE07--x-\\uD83D\\uDE07--]/',

     '\\b*/u',
     '\\b+/u',
     '\\b?/u',
     '\\b{1}/u',
     '\\b**/u',
     '\\b++/u',
     '\\b?+/u',
     '\\b{1}+/u',
     '(?=.)**/u',
     '(?=.)++/u',
     '(?=.)?+/u',
     '(?=.){1}+/u',
     '\\B*/u',
     '\\B+/u',
     '\\B?/u',
     '\\B{1}/u',
     '\\B**/u',
     '\\B++/u',
     '\\B?+/u',
     '\\B{1}+/u',
     '(?!.)**/u',
     '(?!.)++/u',
     '(?!.)?+/u',
     '(?!.){1}+/u',

     '\\A/',
     '\\E/',
     '\\F/',
     '\\G/',
     '\\H/',
     '\\I/',
     '\\J/',
     '\\K/',
     '\\L/',
     '\\M/',
     '\\N/',
     '\\O/',
     // '\\P/',
     '\\Q/',
     '\\R/',
     '\\T/',
     '\\U/',
     '\\V/',
     '\\X/',
     '\\Y/',
     '\\Z/',

     'abc\\a/',
     'abc\\e/',
     'abc\\g/',
     'abc\\h/',
     'abc\\i/',
     'abc\\j/',
     // 'abc\\k/',
     'abc\\l/',
     'abc\\m/',
     'abc\\o/',
     // 'abc\\p/',
     'abc\\q/',
     // 'abc\\u/',
     // 'abc\\x/',
     'abc\\y/',
     'abc\\z/',

     'abc\\A/',
     'abc\\E/',
     'abc\\F/',
     'abc\\G/',
     'abc\\H/',
     'abc\\I/',
     'abc\\J/',
     'abc\\K/',
     'abc\\L/',
     'abc\\M/',
     'abc\\N/',
     'abc\\O/',
     // 'abc\\P/',
     'abc\\Q/',
     'abc\\R/',
     'abc\\T/',
     'abc\\U/',
     'abc\\V/',
     'abc\\X/',
     'abc\\Y/',
     'abc\\Z/',

     '\\ca',
     '\\cb',
     '\\cc',
     '\\cd',
     '\\ce',
     '\\cf',
     '\\cg',
     '\\ch',
     '\\ci',
     '\\cj',
     '\\ck',
     '\\cl',
     '\\cm',
     '\\cn',
     '\\co',
     '\\cp',
     '\\cq',
     '\\cr',
     '\\cs',
     '\\ct',
     '\\cu',
     '\\cv',
     '\\cw',
     '\\cx',
     '\\cy',
     '\\cz',

     '\\cA',
     '\\cB',
     '\\cC',
     '\\cD',
     '\\cE',
     '\\cF',
     '\\cG',
     '\\cH',
     '\\cI',
     '\\cJ',
     '\\cK',
     '\\cL',
     '\\cM',
     '\\cN',
     '\\cO',
     '\\cP',
     '\\cQ',
     '\\cR',
     '\\cS',
     '\\cT',
     '\\cU',
     '\\cV',
     '\\cW',
     '\\cX',
     '\\cY',
     '\\cZ',


     '\\A',
     '\\B',
     '\\D',
     '\\E',
     '\\F',
     '\\G',
     '\\H',
     '\\I',
     '\\J',
     '\\K',
     '\\L',
     '\\M',
     '\\N',
     '\\O',
     '\\P',
     '\\Q',
     '\\R',
     '\\S',
     '\\T',
     '\\U',
     '\\V',
     '\\W',
     '\\X',
     '\\Y',
     '\\Z',

     '\\a',
     '\\b',
     '\\d',
     '\\e',
     '\\f',
     '\\g',
     '\\h',
     '\\i',
     '\\j',
     '\\k',
     '\\l',
     '\\m',
     '\\n',
     '\\o',
     '\\p',
     '\\q',
     '\\r',
     '\\s',
     '\\t',
     '\\u',
     '\\v',
     '\\w',
     '\\x',
     '\\y',
     '\\z',

     'abc\\adeff',
     'abc\\bdeff',
     'abc\\cdeff',
     'abc\\ddeff',
     'abc\\edeff',
     'abc\\fdeff',
     'abc\\gdeff',
     'abc\\hdeff',
     'abc\\ideff',
     'abc\\jdeff',
     'abc\\kdeff',
     'abc\\ldeff',
     'abc\\mdeff',
     'abc\\ndeff',
     'abc\\odeff',
     'abc\\pdeff',
     'abc\\qdeff',
     'abc\\rdeff',
     'abc\\sdeff',
     'abc\\tdeff',
     'abc\\udeff',
     'abc\\vdeff',
     'abc\\wdeff',
     'abc\\xdeff',
     'abc\\ydeff',
     'abc\\zdeff',

     'abc\\Adeff',
     'abc\\Bdeff',
     'abc\\Cdeff',
     'abc\\Ddeff',
     'abc\\Edeff',
     'abc\\Fdeff',
     'abc\\Gdeff',
     'abc\\Hdeff',
     'abc\\Ideff',
     'abc\\Jdeff',
     'abc\\Kdeff',
     'abc\\Ldeff',
     'abc\\Mdeff',
     'abc\\Ndeff',
     'abc\\Odeff',
     'abc\\Pdeff',
     'abc\\Qdeff',
     'abc\\Rdeff',
     'abc\\Sdeff',
     'abc\\Tdeff',
     'abc\\Udeff',
     'abc\\Vdeff',
     'abc\\Wdeff',
     'abc\\Xdeff',
     'abc\\Ydeff',
     'abc\\Zdeff',

     '\\$',
     'abc\\$',
     '\\$abcd',
     'abc\\$abcd',
     '\\_',
     'abc\\_',
     '\\_abcd',
     'abc\\_abcd',

     // '\\x/', '\\x0/', '\\x1/', '\\x2/', '\\x3/', '\\x4/', '\\x5/', '\\x6/', '\\x7/', '\\x8/', '\\x9/',

     // '\\01/', 'a\\02/', '\\03b/', 'a\\04b/', '(a)\\05/', '\\06(b)/', '(\\07)/', '\\08/', '\\09/', '\\00/',

     '/\\2(a)/',

     //'(a)\\3/',
     //'(\\4)/',
     //'\\5x(a)/',
     //'(a)x\\6/',
     //'(a\\7b)/',
     //'0\\8(a)/',
     //'4\\9(a)/',
     //'(a)|\\10/',
     //'\\11|(a)/',
     //'(\\12|a)/',
     //'(a|\\13)/',

     // 'a\\1/',
      // '(a)\\2/',

      '[+9]\\uD83D\\uDE07q\\uD83D(?:q??)\\uDE07\\uDE07\\',


      '\\b*/u',
      '\\b+/u',
      '\\b?/u',
      '\\b{1}/u',
      '\\b**/u',
      '\\b++/u',
      '\\b?+/u',
      '\\b{1}+/u',
      '(?=.)**/u',
      '(?=.)++/u',
      '(?=.)?+/u',
      '(?=.){1}+/u',
      '\\B*/u',
      '\\B+/u',
      '\\B?/u',
      '\\B{1}/u',
      '\\B**/u',
      '\\B++/u',
      '\\B?+/u',
      '\\B{1}+/u',
      '(?!.)**/u',
      '(?!.)++/u',
      '(?!.)?+/u',
      '(?!.){1}+/u',

      //'[b-G\\w]/',
      //'[b-G\\W]/',
      //'[b-G\\0]/',
      //'[b-G\\10]/',
      //'[d-G\\b]/',
      //'[d-G\\B]/',
      //'[d-G\\t]/',
      //'[d-G\\n]/',
      //'[d-G\\v]/',
      //'[d-G\\f]/',
      //'[d-G\\r]/',
      //'[d-G\\c0001]/',
      //'[d-G\\x0061]/',
      //'[d-G\\u0061]/',
      '[d-G\\a]/',
      '\\\rn/',

      // '[\\c0001d-G]/',
      // '[\\x0061d-G]/',
      // '[\\u0061d-G]/',
      '[\\ad-G]/',
      //'[c-eb-a]/',
      // '[b-G\\d]/',
      // '[b-G\\D]/',
      // '[b-G\\s]/',
      // '[b-G\\S]/',

      //'0{2,1}/',
      //'^[z-a]$/',

      'abc/a',
      'a**/',
      'a***/',
      'a++/',
      'a+++/',
      'a???/',

      '(?=b)',
      'a(?=b)',
      '(?=b)c',
      'a(?=b)c',

      '(?:(?:b',
      '(?:(?:b)',
      '(?:(?:b))',
      '(?:a(?:b',
      '(?:a(?:b)',
      '(?:a(?:b))',
      'a(?:a(?:b',
      'a(?:a(?:b)',
      'a(?:a(?:b))',
      '(?x)/',
      '(?',

      '(?:b)',
      'a(?:b)',
      '(?:b)c',
      'a(?:b)c',

      '((b',
      '((b)',
      '((b))',
      '(a(b',
      '(a(b)',
      '(a(b))',
      'a(a(b',
      'a(a(b)',
      'a(a(b))',

      '(b)',
      'a(b)',
      '(b)c',
      'a(b)c',

      //'[x-\\uD83D\\uDE07--+]/',

      // '[--+]/',
      // '[0--]/',
      // '[x---]/',
      // '[0---]/',

      '(?!(?!b',
      '(?!(?!b)',
      '(?!(?!b))',
      '(?!a(?!b',
      '(?!a(?!b)',
      '(?!a(?!b))',
      'a(?!a(?!b',
      'a(?!a(?!b)',
      'a(?!a(?!b))',

      '(?!b)', 'a(?!b)', '(?!b)c', 'a(?!b)c',

      '(?=(?=b',
      '(?=(?=b)',
      '(?=(?=b))',
      '(?=a(?=b',
      '(?=a(?=b)',
      '(?=a(?=b))',
      'a(?=a(?=b',
      'a(?=a(?=b)',
      'a(?=a(?=b))',

      'a(bcde/',
      'a(b(cde/',
      'a(b(?:cd)e/',
      'a(b(?:cde/',
      'a(b(?=cd)e/',
      'a(b(?=cde/',
      'a(b(?!cd)e/',
      'a(b(?!cde/',
      'a(?:b(cd)e/',
      'a(?:b(cde/',
      'a(?:b(?:cd)e/',
      'a(?:b(?:cde/',
      'a(?:b(?=cd)e/',
      'a(?:b(?=cde/',
      'a(?:b(?!cd)e/',
      'a(?:b(?!cde/',
      'a(?=b(cd)e/',
      'a(?=b(cde/',
      'a(?=b(?:cd)e/',
      'a(?=b(?:cde/',
      'a(?=b(?=cd)e/',
      'a(?=b(?=cde/',
      'a(?=b(?!cd)e/',


      'a(?!b(c)de/',
      'a(?!b(cde/',
      'a(?!b(?:cd)e/',
      'a(?!b(?:cde/',
      'a(?!b(?=cd)e/',
      'a(?!b(?=cde/',
      'a(?!b(?!cd)e/',
      'a(?!b(?!cde/',

      'a????/',
      'a+++/',
      //'x{1}{1,}/',
      //'x{1,2}{1}/',
      //'x{1,}{1}/',
      //'x{0,1}{1,}/',

      '++a/',
      '?a/',
      '??a/',
      // '[b-ac-e]/',
      // '[a-dc-b]/',
      // '[\\db-G]/',
      // '[\\Db-G]/',
      // '[\\sb-G]/',
      // '[\\Sb-G]/',
      // '[\\wb-G]/',
      // '[\\Wb-G]/',
      // '[\\0b-G]/',
      // '[\\10b-G]/',
      // '[\\bd-G]/',
      // '[\\Bd-G]/',
      // '[\\td-G]/',
      // '[\\nd-G]/',
      // '[\\vd-G]/',
      // '[\\fd-G]/',
      // '[\\rd-G]/',

     '\\Aabcd',
     '\\Babcd',
     '\\Cabcd',
     '\\Dabcd',
     '\\Eabcd',
     '\\Fabcd',
     '\\Gabcd',
     '\\Habcd',
     '\\Iabcd',
     '\\Jabcd',
     '\\Kabcd',
     '\\Labcd',
     '\\Mabcd',
     '\\Nabcd',
     '\\Oabcd',
     '\\Pabcd',
     '\\Qabcd',
     '\\Rabcd',
     '\\Sabcd',
     '\\Tabcd',
     '\\Uabcd',
     '\\Vabcd',
     '\\Wabcd',
     '\\Xabcd',
     '\\Yabcd',
     '\\Zabcd',

     '\\aabcd',
     '\\babcd',
     '\\cabcd',
     '\\dabcd',
     '\\eabcd',
     '\\fabcd',
     '\\gabcd',
     '\\habcd',
     '\\iabcd',
     '\\jabcd',
     '\\kabcd',
     '\\labcd',
     '\\mabcd',
     '\\nabcd',
     '\\oabcd',
     '\\pabcd',
     '\\qabcd',
     '\\rabcd',
     '\\sabcd',
     '\\tabcd',
     '\\uabcd',
     '\\vabcd',
     '\\wabcd',
     '\\xabcd',
     '\\yabcd',
     '\\zabcd',

     'abc\\A',
     'abc\\B',
     'abc\\D',
     'abc\\E',
     'abc\\F',
     'abc\\G',
     'abc\\H',
     'abc\\I',
     'abc\\J',
     'abc\\K',
     'abc\\L',
     'abc\\M',
     'abc\\N',
     'abc\\O',
     'abc\\P',
     'abc\\Q',
     'abc\\R',
     'abc\\S',
     'abc\\T',
     'abc\\U',
     'abc\\V',
     'abc\\W',
     'abc\\X',
     'abc\\Y',
     'abc\\Z',

     'abc\\a',
     'abc\\b',
     'abc\\d',
     'abc\\e',
     'abc\\f',
     'abc\\g',
     'abc\\h',
     'abc\\i',
     'abc\\j',
     'abc\\k',
     'abc\\l',
     'abc\\m',
     'abc\\n',
     'abc\\o',
     'abc\\p',
     'abc\\q',
     'abc\\r',
     'abc\\s',
     'abc\\t',
     'abc\\u',
     'abc\\v',
     'abc\\w',
     'abc\\x',
     'abc\\y',
     'abc\\z',

    ];

    for (const arg of InValidNonUnicodeCases) {
       fail(`Fail ${arg}`, {
        name: `${arg}`,
        source: `${arg}`,
        value: 'foo',
        raw: 'foo',
        context: Context.OptionsAnnexB,
        token: Token.Identifier,
        line: 1,
        column: 3,
    });
    }

    const ValidNonUnicodeCases = [

      '\\cA/',
      '\\cB/',
      '\\cD/',
      '\\cE/',
      '\\cF/',
      '\\cG/',
      '\\cH/',
      '\\cI/',
      '\\cJ/',
      '\\cK/',
      '\\cL/',
      '\\cM/',
      '\\cN/',
      '\\cO/',
      '\\cP/',
      '\\cQ/',
      '\\cR/',
      '\\cS/',
      '\\cT/',
      '\\cU/',
      '\\cV/',
      '\\cW/',
      '\\cX/',
      '\\cY/',
      '\\cZ/',

      '\\ca/',
      '\\cb/',
      '\\cd/',
      '\\ce/',
      '\\cf/',
      '\\cg/',
      '\\ch/',
      '\\ci/',
      '\\cj/',
      '\\ck/',
      '\\cl/',
      '\\cm/',
      '\\cn/',
      '\\co/',
      '\\cp/',
      '\\cq/',
      '\\cr/',
      '\\cs/',
      '\\ct/',
      '\\cu/',
      '\\cv/',
      '\\cw/',
      '\\cx/',
      '\\cy/',
      '\\cz/',

      '[--0]/',
      '[+--]/',

      '[-+]/',
      '[+-]/',
      '[---+]/',
      '[---0]/',
      '[-]/',
      '[--]/',
      '[---]/',
      '[----]/',
      '[-----]/',
      '[------]/',
      '[-------]/',
      '[--------]/',
      '[---------]/',

        //'[\\uD83D\\uDCA9]/',
       // '[\\uD83D\\uDCAB]/',

       // '[\\x01-\\x17]/',
       '[\\u0001-\\x17]/',
       // '[\\x01-\\u0007]/',
       // '[\\x01-\\x17]/',
       '[A-\\cH]/',
       '[\\cH-Z]/',

       '[a-z\\dx]/',
       '[A-Z\\Dx]/',
       '[a-z\\sx]/',
       '[A-S\\Sx]/',
       '[a-z\\wx]/',
       '[A-Z\\Wx]/',
       '[a-z\\d]/',
       '[A-Z\\D]/',
       '[a-z\\s]/',
       '[A-S\\S]/',
       '[a-z\\w]/',
       '[A-Z\\W]/',

       '[\\u1234]/',
       '[x\\u0567]/',
       '[\\uf89ay]/',
       '[x\\ubcdey]/',

       '[\\da-z]/',
       '[\\DA-Z]/',
       '[\\sa-z]/',
       '[\\SA-S]/',
       '[\\wa-z]/',
       '[\\WA-Z]/',

       '[\\d-z]/',
       '[\\D-Z]/',
       '[\\s-z]/',
       '[\\S-S]/',
       '[\\w-z]/',
       '/[\\W-Z]/',

       // '[\\ud800]/',
       // '[x\\ud810]/',
       // '[\\ud900y]/',
       // '[x\\udabcy]/',
       // '[x\\udabcy]/g',
       // '[x\\udabcy]/m',
       // '[x\\udabcy]/iy',
       //'[\\ud800\\ud800\\udc00]/',

       // '[x\\ud810\\ud810\\udc10]/',
       // '[\\ud900\\ud900\\udd00y]/',
       // '[x\\udabc\\udabc\\udebcy]/',

       // '[\\ud800\\udc00\\udc00]/',
       // '[x\\ud810\\udc10\\udc10]/',
       // '[\\ud900\\udd00\\udd00y]/',
       // '[x\\udabc\\udebc\\udebcy]/',

       // '[\\ud800\\udc00\\ud800]/', '[x\\ud810\\udc10\\ud810]/', '[\\ud900\\udd00\\ud900y]/', '[x\\udabc\\udebc\\udabcy]/',

      '[\\$]/',
      '[abc\\$]/',
      '[\\$abcd]/',
      '[abc\\$abcd]/',

      `[\\^]/`,
      `[\\$]/`,

      `[\\\\]/`,
      `[\\.]/`,
      `[\\*]/`,

      `[\\+]/`,
      `[\\?]/`,
      `[\\(]/`,
      `[\\)]/`,

      `[\\[]/`,
      `[\\]]/`,
      `[\\{]/`,
      `[\\}]/`,
      `[\\|]/`,

      '[\\d]/',
      '[\\D]/',
      '[\\f]/',
      '[\\n]/',
      '[\\r]/',
      '[\\s]/',
      '[\\S]/',
      '[\\t]/',
      '[\\v]/',
      '[\\w]/',
      '[\\W]/',

      '[abc\\d]/',
      '[abc\\D]/',
      '[abc\\f]/',
      '[abc\\n]/',
      '[abc\\r]/',
      '[abc\\s]/',
      '[abc\\S]/',
      '[abc\\t]/',
      '[abc\\v]/',
      '[abc\\w]/',
      '[abc\\W]/',

      '[\\fabcd]/',
      '[\\dabcd]/',
      '[\\Dabcd]/',
      '[\\nabcd]/',
      '[\\rabcd]/',
      '[\\sabcd]/',
      '[\\Sabcd]/',
      '[\\tabcd]/',
      '[\\vabcd]/',
      '[\\wabcd]/',
      '[\\Wabcd]/',

      '[abc\\fdeff]/',
      '[abc\\ddeff]/',
      '[abc\\Ddeff]/',
      '[abc\\ndeff]/',
      '[abc\\rdeff]/',
      '[abc\\sdeff]/',
      '[abc\\Sdeff]/',
      '[abc\\tdeff]/',
      '[abc\\vdeff]/',
      '[abc\\wdeff]/',
      '[abc\\Wdeff]/',

      '[\\0]/',
      '[a\\0]/',
      '[\\0b]/',
      '[a\\0b]/',
      '[0\\0b]/',
      '[1\\0b]/',
      '\\1(a)/',
      '(a)\\1/',
      '(\\1)/',
      '\\1x(a)/',
      '(a)x\\1/',
      '(a\\1b)/',
      '0\\1(a)/',
      '4\\1(a)/',
      '(a)|\\1/',
      '\\1|(a)/',
      '(\\1|a)/',
      '(a|\\1)/',
      '\\0/',
      '(a)\\0/',
      '(a)\\1/',
      '((a))\\1/',
      '((a))\\2/',
      '(((a)))\\2/',
      '(((a)))\\3/',
      '((((a))))\\3/',
      '((((a))))\\4/',
      '(((((a)))))\\4/',
      '(((((a)))))\\5/',
      '((((((a))))))\\5/',
      '((((((a))))))\\6/',
      '(((((((a)))))))\\6/',
      '(((((((a)))))))\\7/',
      '((((((((a))))))))\\7/',
      '((((((((a))))))))\\8/',
      '(((((((((a)))))))))\\8/',
      '(((((((((a)))))))))\\9/',
      '((((((((((a))))))))))\\9/',
      '((((((((((a))))))))))\\10/',
      '(((((((((((a)))))))))))\\10/',
      '(((((((((((a)))))))))))\\11/',
      '((((((((((((a))))))))))))\\11/',
      '((((((((((((a))))))))))))\\12/',
      '(((((((((((((a)))))))))))))\\12/',
      '(((((((((((((a)))))))))))))\\13/',
      '((((((((((((((a))))))))))))))\\13/',
      '((((((((((((((a))))))))))))))\\14/',
      '(((((((((((((((a)))))))))))))))\\14/',
      '(((((((((((((((a)))))))))))))))\\15/',
      '((((((((((((((((a))))))))))))))))\\15/',
      '((((((((((((((((a))))))))))))))))\\16/',
      '(((((((((((((((((a)))))))))))))))))\\16/',
      '(((((((((((((((((a)))))))))))))))))\\17/',
      '((((((((((((((((((a))))))))))))))))))\\17/',
      '((((((((((((((((((a))))))))))))))))))\\18/',
      '(((((((((((((((((((a)))))))))))))))))))\\18/',
      '(((((((((((((((((((a)))))))))))))))))))\\19/',
      '((((((((((((((((((((a))))))))))))))))))))\\19/',
      '((((((((((((((((((((a))))))))))))))))))))\\20/',
      '(((((((((((((((((((((a)))))))))))))))))))))\\20/',
      '\\1x(a)/',
      '\\ud800/', 'x\\ud810/', '\\ud900y/', 'x\\udabcy/', 'x\\udabcy/g', 'x\\udabcy/m', 'x\\udabcy/iy',
      '\\ud800\\ud800/', 'x\\ud810\\ud810/', '\\ud900\\ud900y/', 'x\\udabc\\udabcy/',
      '\\udc00/', 'x\\udc10/', '\\udd00y/', 'x\\udebcy/', 'x\\udebcy/g', 'x\\udebcy/im', 'x\\udebcy/y',
      '\\udc00\\udc00/', 'x\\udc10\\udc10/', '\\udd00\\udd00y/', 'x\\udebc\\udebcy/', 'x\\udebc\\udebcy/i',
      '\\ud800\\udc00/', 'x\\ud810\\udc10/', '\\ud900\\udd00y/', 'x\\udabc\\udebcy/', 'x\\udabc\\udebcy/g',
      '\\u1234\\ud800/', 'x\\u0567\\ud810/', '\\uf89a\\ud900y/', 'x\\ubcde\\udabcy/', 'x\\ubcde\\udabcy/m',
      '\\u1234\\udc00/', 'x\\u0567\\udc10/', '\\uf89a\\udd00y/', 'x\\ubcde\\udebcy/', 'x\\ubcde\\udebcy/y',
      '\\u1234\\u1234\\udc00/', 'x\\u0567\\u0567\\udc10/', '\\uf89a\\uf89a\\udd00y/', 'x\\ubcde\\ubcde\\udebcy/',
      '\\u1234\\udc00\\udc00/', 'x\\u0567\\udc10\\udc10/', '\\uf89a\\udd00\\udd00y/', 'x\\ubcde\\udebc\\udebcy/',
      '\\ud800\\ud800\\udc00/', 'x\\ud810\\ud810\\udc10/', '\\ud900\\ud900\\udd00y/', 'x\\udabc\\udabc\\udebcy/',
      '\\ud800\\udc00\\udc00/', 'x\\ud810\\udc10\\udc10/', '\\ud900\\udd00\\udd00y/', 'x\\udabc\\udebc\\udebcy/',
      '\\ud800\\udc00\\ud800/', 'x\\ud810\\udc10\\ud810/', '\\ud900\\udd00\\ud900y/', 'x\\udabc\\udebc\\udabcy/',

      '\\cA/',
      '\\cB/',
      '\\cD/',
      '\\cE/',
      '\\cF/',
      '\\cG/',

      '\\$/',
      'abc\\$/',
      '\\$abcd/',
      'abc\\$abcd/',

      `\\^/`,
      `\\$/`,
      //`\\\\/`,
      `\\./`,
      `\\*/`,
      `\\+/`,
      `\\?/`,
      // `\\(/`,
      //`\\)/`,
      //`\\[/`,
      `\\]/`,
      `\\{/`,
      `\\}/`,
      `\\|/`,

      //`\\'/`,
      //`\\"/`,
      // `\\\`/`,

      '\\ca/',
      '\\cb/',
      '\\cd/',
      '\\ce/',
      '\\cf/',
      '\\cg/',
      '\\ch/',
      '\\ci/',
      '\\cj/',
      '\\ck/',
      '\\cl/',
      '\\cm/',
      '\\cn/',
      '\\co/',
      '\\cp/',
      '\\cq/',
      '\\cr/',
      '\\cs/',
      '\\ct/',
      '\\cu/',
      '\\cv/',
      '\\cw/',
      '\\cx/',
      '\\cy/',
      '\\cz/',

      '\\cH/',
      '\\cI/',
      '\\cJ/',
      '\\cK/',
      '\\cL/',
      '\\cM/',
      '\\cN/',
      '\\cO/',
      '\\cP/',
      '\\cQ/',
      '\\cR/',
      '\\cS/',
      '\\cT/',
      '\\cU/',
      '\\cV/',
      '\\cW/',
      '\\cX/',
      '\\cY/',
      '\\cZ/',

      'abc\\fdeff/',
      'abc\\ddeff/',
      'abc\\Ddeff/',
      'abc\\ndeff/',
      'abc\\rdeff/',
      'abc\\sdeff/',
      'abc\\Sdeff/',
      'abc\\tdeff/',
      'abc\\vdeff/',
      'abc\\wdeff/',
      'abc\\Wdeff/',

      '\\fabcd/',
      '\\dabcd/',
      '\\Dabcd/',
      '\\nabcd/',
      '\\rabcd/',
      '\\sabcd/',
      '\\Sabcd/',
      '\\tabcd/',
      '\\vabcd/',
      '\\wabcd/',
      '\\Wabcd/',

      '\\d/',
      '\\D/',
      '\\f/',
      '\\n/',
      '\\r/',
      '\\s/',
      '\\S/',
      '\\t/',
      '\\v/',
      '\\w/',
      '\\W/',

      'abc\\d/',
      'abc\\D/',
      'abc\\f/',
      'abc\\n/',
      'abc\\r/',
      'abc\\s/',
      'abc\\S/',
      'abc\\t/',
      'abc\\v/',
      'abc\\w/',
      'abc\\W/',

      `[a]/`,
      `[b]/`,
      `[c]/`,
      `[d]/`,
      `[e]/`,
      `[f]/`,
      `[g]/`,
      `[h]/`,
      `[i]/`,
      `[j]/`,
      `[k]/`,
      `[l]/`,
      `[m]/`,
      `[n]/`,
      `[o]/`,
      `[p]/`,
      `[q]/`,
      `[r]/`,
      `[s]/`,
      `[t]/`,
      `[u]/`,
      `[v]/`,
      `[w]/`,
      `[x]/`,
      `[y]/`,
      `[z]/`,

      `[A]/`,
      `[B]/`,
      `[C]/`,
      `[D]/`,
      `[E]/`,
      `[F]/`,
      `[G]/`,
      `[H]/`,
      `[I]/`,
      `[J]/`,
      `[K]/`,
      `[L]/`,
      `[M]/`,
      `[N]/`,
      `[O]/`,
      `[P]/`,
      `[Q]/`,
      `[R]/`,
      `[S]/`,
      `[T]/`,
      `[U]/`,
      `[V]/`,
      `[W]/`,
      `[X]/`,
      `[Y]/`,
      `[Z]/`,
      `[rD]/`,
      `[Kq]/`,
      `[$%]/`,
      `[-]/`,
      `[-b]/`,
      `[a-]/`,
      '[^-J]/g',
      '[^J-]/g',
      '[^--]/g',
      '[^---]/g',

      `[\\b]/`, `[a\\bc]/`, `[\\bc]/`, `[a\\bb]/`,
      `[\\-]/`, `[a\\-c]/`, `[\\-c]/`, `[a\\-b]/`,

      `[abc\\^]/`,
      `[abc\\$]/`,
      `[abc\\\\]/`,
      `[abc\\.]/`,
      `[abc\\*]/`,
      `[abc\\+]/`,
      `[abc\\?]/`,
      `[abc\\(]/`,
      `[abc\\)]/`,
      `[abc\\[]/`,
      `[abc\\]]/`,
      `[abc\\{]/`,
      `[abc\\}]/`,
      `[abc\\|]/`,

      `[\\^def]/`,
      `[\\$def]/`,
      `[\\\\def]/`,
      `[\\.def]/`,
      `[\\*def]/`,
      `[\\+def]/`,
      `[\\?def]/`,
      `[\\(def]/`,
      `[\\)def]/`,
      `[\\[def]/`,
      `[\\]def]/`,
      `[\\{def]/`,
      `[\\}def]/`,
      `[\\|def]/`,

      '[\\ca]/',
      '[\\cb]/',
      '[\\cd]/',
      '[\\ce]/',
      '[\\cf]/',
      '[\\cg]/',
      '[\\ch]/',
      '[\\ci]/',
      '[\\cj]/',
      '[\\ck]/',
      '[\\cl]/',
      '[\\cm]/',
      '[\\cn]/',
      '[\\co]/',
      '[\\cp]/',
      '[\\cq]/',
      '[\\cr]/',
      '[\\cs]/',
      '[\\ct]/',
      '[\\cu]/',
      '[\\cv]/',
      '[\\cw]/',
      '[\\cx]/',
      '[\\cy]/',
      '[\\cz]/',

      '[\\cA]/',
      '[\\cB]/',
      '[\\cD]/',
      '[\\cE]/',
      '[\\cF]/',
      '[\\cG]/',
      '[\\cH]/',
      '[\\cI]/',
      '[\\cJ]/',
      '[\\cK]/',
      '[\\cL]/',
      '[\\cM]/',
      '[\\cN]/',
      '[\\cO]/',
      '[\\cP]/',
      '[\\cQ]/',
      '[\\cR]/',
      '[\\cS]/',
      '[\\cT]/',
      '[\\cU]/',
      '[\\cV]/',
      '[\\cW]/',
      '[\\cX]/',
      '[\\cY]/',
      '[\\cZ]/',

      '(b)/', 'a(b)/', '(b)c/', 'a(b)c/',
      '((b))/',
      '(a(b))/',
      'a(a(b))/',
      '(a(b))c/',
      'a(a(b))c/',
      '((b)c)/',
      'a((b)c)/',
      '((b)c)c/',
      'a((b)c)c/',
      '(a(b)c)/',
      'a(a(b)c)/',
      '(a(b)c)c/',
      'a(a(b)c)c/',
      '()/',
      '(?:b)/',
      'a(?:b)/',
      '(?:b)c/',
      'a(?:b)c/',
      '(?:)/',
      '(?=b)/',
      'a(?=b)/',
      '(?=b)c/',
      'a(?=b)c/',
      '(?=(?=b))/',
      '(?=a(?=b))/',
      '(?=)/',
      '(?!b)/',
      'a(?!b)/',
      '(?!b)c/',
      'a(?!b)c/',
      '(?!(?!b))/',
      '(?!)/',
      'a(b(c)d)e/',
      '[^]a/m',
      'a[^]/',
      'a[^b-z]\\s+/',
      '[^\\b]+/g',
      'a[^1-9]c/',
      'a[^b]c/',
      '[^a-z]{4}/',
      '.[\\b]./',
      'c[\\b]{3}d/',
      '[^\\[\\b\\]]+/',
      '\\u0042/i',
      '1?1/mig',
      'a(b(?:c)d)e/',
      'a(b(?=c)d)e/',
      'a(b(?!c)d)e/',
      'a(?:b(c)d)e/',
      'a(?:b(?:c)d)e/',
      'a(?:b(?=c)d)e/',
      'a(?:b(?!c)d)e/',
      'a(?=b(c)d)e/',
      'a(?=b(?:c)d)e/',
      'a(?=b(?=c)d)e/',
      'a(?=b(?!c)d)e/',
      'a(?!b(c)d)e/',
      'a(?!b(?:c)d)e/',
      'a(?!b(?=c)d)e/',
      'a(?!b(?!c)d)e/',
      '(?!a(?!b))/',
      'a(?!a(?!b))/',
      '(?!a(?!b))c/',
      'a(?!a(?!b))c/',
      '(?!(?!b)c)/',
      'a(?!(?!b)c)/',
      '(?!(?!b)c)c/',
      'a(?!(?!b)c)c/',
      '(?!a(?!b)c)/',
      'a(?!a(?!b)c)/',
      '(?!a(?!b)c)c/',
      'a(?!a(?!b)c)c/',
      'a(?=a(?=b))/',
      '(?=a(?=b))c/',
      'a(?=a(?=b))c/',
      '(?=(?=b)c)/',
      'a(?=(?=b)c)/',
      '(?=(?=b)c)c/',
      'a(?=(?=b)c)c/',
      '(?=a(?=b)c)/',
      'a(?=a(?=b)c)/',
      '(?=a(?=b)c)c/',
      'a(?=a(?=b)c)c/',
      '(?:(?:b))/',
      '(?:a(?:b))/',
      'a(?:a(?:b))/',
      '(?:a(?:b))c/',
      'a(?:a(?:b))c/',
      '(?:(?:b)c)/',
      'a(?:(?:b)c)/',
      '(?:(?:b)c)c/',
      'a(?:(?:b)c)c/',
      '(?:a(?:b)c)/',
      'a(?:a(?:b)c)/',
      '(?:a(?:b)c)c/',
      'a(?:a(?:b)c)c/',

      '\\??\\??\\??\\??\\??/',
      '.?.?.?.?.?.?.?/',
      'b{2,}c/',
      'b{8,}c/',
      '\\d{1,}/',
      '(123){1,}/',
      '(123){1,}x\\1/',
      'x{1,2}x{1,}/',
      '(?=(a+))/',
      '(?=(a+))a*b\\1/',
      // '[Jj]ava([Ss]cript)?(?=\\:)/',
      '(.*?)a(?!(a+)b\\2c)\\2(.*)/',
      'Java(?!Script)([A-Z]\\w*)/',
      'Java(?!Script)([A-Z]\\w*)/',
      //  '(\\.(?!com|org)|\\/)/',

      // '\\;/',
       // '\\ /',
       // '\\:/',

       // '\\%([0-9]*)\\[(\\^)?(\\]?[^\\]]*)\\]/',
       // '\\%([0-9]*)\\[(\\^)?\\]/',
       '(\\]?[^\\]]*)\\]/',

      'abc/gim',
      'a|ab/',
      '((a)|(ab))((c)|(bc))/',
      '\\d{3}|[a-z]{4}/',
      '\\d{3}|[a-z]{4}/',
      'ab|cd|ef/i',
      'ab|cd|ef/',
      '(?:ab|cd)+|ef/i',
      '(?:ab|cd)+|ef/i',
      '11111|111/',
      'xyz|.../',
      '(.)..|abc/',
      '.+: gr(a|e)y/',
      '(Rob)|(Bob)|(Robert)|(Bobby)/',
      '()|/',
      '|()/',
      'a[a-z]{2,4}/',
      'a[a-z]{2,4}?/',
      '(aa|aabaac|ba|b|c)*/',
      '(z)((a+)?(b+)?(c))*/',
      '(a*)b\\1+/',
      's$/',
      'e$/',
      's$/m',
      '[^e]$/mg',
      'es$/mg',
      '^m/',
      '^m/m',
      '^p[a-z]/',
      '^p[b-z]/m',
      '^[^p]/m',
      '^ab/',
      '^..^e/',
      '^xxx/',
      '^\\^+/',
      '^\\d+/m',
      '\\bp/',
      'ot\\b/',
      '\\bot/',
      '\\bso/',
      'so\\b/',
      '[^o]t\\b/',
      '[^o]t\\b/i',
      '\\bro/',
      'r\\b/',
      '\\brobot\\b/',
      '\\b\\w{5}\\b/',
      '\\bop/',
      'op\\b/',
      'e\\b/',
      '\\be/',
      '\\Bevil\\B/',
      '[f-z]e\\B/',
      '\\Bo\\B/i',
      '\\B\\w\\B/',
      '\\w\\B/',
      '\\B\\w/',
      '\\B[^z]{4}\\B/',
      '\\B\\w{4}\\B/',
      '^^^^^^^robot$$$$/',

      '\\B\\B\\B\\B\\B\\Bbot\\b\\b\\b\\b\\b\\b\\b/',
      '^.*?$/',
      '^.*?/',
      '^.*?(:|$)/',
      '^.*(:|$)/',
      '\\d{2,4}/',
      'b{2,3}c/',
      'b{42,93}c/',
      'b{0,93}c/',
      'bx{0,93}c/',
      '.{0,93}/',
      '\\w{3}\\d?/',
      '\\w{3}\\d?/',
      'b{2}c/',
      'b{8}/',
      '\\s+java\\s+/',
      '[a-z]+\\d+/',
      '[a-z]+\\d+/',
      '[a-z]+(\\d+)/',
      'd+/',
      'o+/',
      '(b+)(b+)(b+)/',
      '(b+)(b*)/',
      'b*b+/',
      '[^"]*/',
      '[^"]*/',

      '[^"]*/',
      `["'][^"']*["']/`,
      '(x*)(x+)/',
      '(\\d*)(\\d+)/',
      '(\\d*)\\d(\\d+)/',
      '(x+)(x*)/',
      'x*y+$/',
      '[\\d]*[\\s]*bc./',
      'bc..[\\d]*[\\s]*/',
      '[xyz]*1/',
      'java(script)?/',
      'x?y?z?/',
      'x?ay?bz?c/',
      'ab?c?d?x?y?z/',
      '(?!a|b)|c/',
      '([Jj]ava([Ss]cript)?)\\sis\\s(fun\\w*)/',
      '(.{3})(.{4})/',
      '(aa)bcd\\1/',
      '(aa).+\\1/',
      '(.{2}).+\\1/',
      '(\\d{3})(\\d{3})\\1\\2/',
      'a(..(..)..)/',
      '(a(b(c)))(d(e(f)))/',
      '(a(b(c)))(d(e(f)))\\2\\5/',
      'a(.?)b\\1c\\1d\\1/',

      'a(.?)b\\1c\\1d\\1/',
      //'<body.*>((.*\\n?)*?)<\\/body>/i',
      '(\\|)([\\w\\x81-\\xff ]*)(\\|)([\\/a-z][\\w:\\/\\.]*\\.[a-z]{3,4})(\\|)/ig',
      '([\\S]+([ \\t]+[\\S]+)*)[ \\t]*=[ \\t]*[\\S]+/',
      '^(A)?(A.*)$/',
      '(a)?a/',
      'a|(b)/',
      '(a)?(a)/',
      '^([a-z]+)*[a-z]$/',
      '^(([a-z]+)*[a-z]\\.)+[a-z]{2,}$/',
      '^(([a-z]+)*([a-z])\\.)+[a-z]{2,}$/',

      '.*a.*/',
      '.+/',
      '[a-z]+/ig',
      '[a-z]+/',
      '\\b(\\w+) \\1\\b/',
      '([xu]\\d{2}([A-H]{2})?)\\1/',
      '([xu]\\d{2}([A-H]{2})?)\\1/',
      '(a*)b\\1+/',
      '((((((((((A))))))))))\\1\\2\\3\\4\\5\\6\\7\\8\\9\\10/',
      '((((((((((A))))))))))\\10\\9\\8\\7\\6\\5\\4\\3\\2\\1/',
      '[]a/',
      'q[ax-zb](?=\\s+)/',
      'ab[ercst]de/',
      '[d-h]+/',
      '[1234567].{2}/',
      '[a-c\\d]+/',
      'ab[.]?c/',
      'a[b]c/',
      '[a-z][^1-9][a-z]/',
      '[*&$]{3}/',
      '[\\d][\\n][^\\d]/',

      `a{0}/`,
      `a{1}/`,
      `a{2}/`,
      `a{3}/`,
      `a{4}/`,
      `a{5}/`,
      `a{6}/`,
      `a{7}/`,
      `a{8}/`,
      `a{9}/`,
      `a{11}/`,
      `a{12}/`,
      `a{23}/`,
      `a{34}/`,
      `a{45}/`,
      `a{56}/`,
      `a{67}/`,
      `a{78}/`,
      `a{89}/`,
      `a{90}/`,
      `a{0,}/`,
      `a{1,}/`,
      `a{2,}/`,
      `a{3,}/`,
      `a{4,}/`,
      `a{5,}/`,
      `a{6,}/`,
      `a{7,}/`,
      `a{8,}/`,
      `a{9,}/`,

      `a{11,}/`,
      `a{12,}/`,
      `a{23,}/`,
      `a{34,}/`,
      `a{45,}/`,
      `a{56,}/`,
      `a{67,}/`,
      `a{78,}/`,
      `a{89,}/`,
      `a{90,}/`,
      `a{0,0}/`,
      `a{1,1}/`,
      `a{2,2}/`,
      `a{3,3}/`,
      `a{4,4}/`,
      `a{5,5}/`,
      `a{6,6}/`,
      `a{7,7}/`,
      `a{8,8}/`,
      `a{9,9}/`,
      `a{0,15}/`,
      `a{1,16}/`,
      `a{2,27}/`,
      `a{3,38}/`,
      `a{4,49}/`,
      `a{5,50}/`,
      `a{6,61}/`,
      `a{7,72}/`,
      `a{8,83}/`,
      `a{9,94}/`,

      `a{11,15}/`,
      `a{12,26}/`,
      `a{23,37}/`,
      `a{34,48}/`,
      `a{45,59}/`,
      `a{56,60}/`,
      `a{67,71}/`,
      `a{78,82}/`,
      `a{89,93}/`,
      `a{90,94}/`,

      `a{,0}/`,
      `a{,1}/`,
      `a{,2}/`,
      `a{,3}/`,
      `a{,4}/`,
      `a{,5}/`,
      `a{,6}/`,
      `a{,7}/`,
      `a{,8}/`,
      `a{,9}/`,

      `a{,15}/`,
      `a{,16}/`,
      `a{,27}/`,
      `a{,38}/`,
      `a{,49}/`,
      `a{,50}/`,
      `a{,61}/`,
      `a{,72}/`,
      `a{,83}/`,
      `a{,94}/`,

      'foo/g',
      'foo/i',
      'foo/m',

      'foo/ig',
      'foo/mi',
      'foo/gy',

      '\\d/',
      '\\D/',
      '\\f/',
      '\\n/',
      '\\r/',
      '\\s/',
      '\\S/',
      '\\t/',
      '\\v/',
      '\\w/',
      '\\W/',

      'abc\\d/',
      'abc\\D/',
      'abc\\f/',
      'abc\\n/',
      'abc\\r/',
      'abc\\s/',
      'abc\\S/',
      'abc\\t/',
      'abc\\v/',
      'abc\\w/',
      'abc\\W/',

      '\\fabcd/',
      '\\dabcd/',
      '\\Dabcd/',
      '\\nabcd/',
      '\\rabcd/',
      '\\sabcd/',
      '\\Sabcd/',
      '\\tabcd/',
      '\\vabcd/',
      '\\wabcd/',
      '\\Wabcd/',

      'abc\\fdeff/',
      'abc\\ddeff/',
      'abc\\Ddeff/',
      'abc\\ndeff/',
      'abc\\rdeff/',
      'abc\\sdeff/',
      'abc\\Sdeff/',
      'abc\\tdeff/',
      'abc\\vdeff/',
      'abc\\wdeff/',
      'abc\\Wdeff/',

      `$abc/u`,
      `abc$abc/u`,
      `a*/u`,
      `a?/u`,
      `a+/u`,
      `|a/u`,
      `a|/u`,
      `|/u`,
      'a||/u',
      `a|b/u`,
      `abc/u`,
      '\\u000A/',
      '\\uFFFF/',
      '\\u0042/',
      '\\u0047/',
      '\\u000A/',
      '\\u000A/',

      // '\\09',
      // '\\00',
      // '\\2(a)/',
      // '(a)\\3/',
      // '(\\4)/',

//      '/foo/',

'foo/',
'foo|bar/',

'||||/',
'^|$|\\b|\\B/',
'(?=)/',
'(?=a)*/',
'(?=a)+/',
'(?=a)?/',
'(?=a)*/',
'(?=a)+/',
'(?=a)?/',
'(?=a){/',
'(?=a){}/',
'(?=a){a}/',
'(?=a){1}/',
'(?=a){1,}/',
'(?=a){1,2}/',
'a*/',
'a+/',

"(?!)/",
"(?!)/u",
"(?=a)?/",
"(?=a){/",
"a{1,/",
"a{1,2}/",
"a{1,2/",
"a{2,1/",
"a{?/",

//"a{a}?/",
"a{1}?/",

"👍🚀❇️/",
"^/",
"$/",
"$/u",
"]/",
"|/",
"\\1/",
"(?:a)\\1/",
"(a)(a)(a)(a)(a)(a)(a)(a)(a)(a)\\11/",
"(?:a)/",
"\\s/",

"\\cA/",

"\\400/",
"\\+/",
"[]/",

"[^-a-b-]/",
"[^-a-b-]/u",
"[a]/u",
"[a-]/",
"[---]/",
"[b\\-a]/",
"[\\d]/u",
"[\\t]/",
"[\\v]/",
"[\\0]/",
"[\\x12]/",
//"[\\u1]/",
"[\\u1234]/",
"[\\377]/",
"[\\[]/",
"[\\[]/u",
//"[\\a]/",
// "[\\W-\\uFFFF]/",
"^https?:\\/\\//",
"^\\d{1,3}(.\\d{1,3}){3}$/",
"^-?([1-9][0-9]*|0)(\\.[0-9]+)?$/",
"^-?([1-9][0-9]*|0)(\\.[0-9]+)?$/u",
"^[ｧ-ﾝﾞﾟ\\-]*$/",
"^[^\\x20-\\x7e]*$/",
"^((4\\d{3})|(5[1-5]\\d{2})|(6011))([- ])?\\d{4}([- ])?\\d{4}([- ])?\\d{4}|3[4,7]\\d{13}$/",
"^\\s*|\\s*$/",
"[\\d][\\12-\\14]{1,}[^\\d]/",
"([a ]\\b)*\\b/",
"(?<=a)/",
"(?<=a)/u",
"(?<!a)/",
//"(?<=(?<a>\\w){3})f/",
"((?<=\\w{3}))f/",

"(a)/",
"(?:a)/",
"\\k/",
"\\k<a>/",
// "(?<a>a)\\k<a>/",
// "(?<a>a)\\1/",
//"(?<a>a)(?<b>a)/",

"\\p/",
//"\\p{/",
// "\\p{ASCII/",
"\\p{ASCII}/",
"\\p{ASCII}/u",
"\\p{Emoji}/u",
"\\p{Script=Hiragana}/u",
"\\P{Letter}/u",
// "(?<=(?<a>\\w){3})f/u",
"((?<=\\w{3}))f/u",
//"(?<=(?<a>\\w){3})f/",
//"(?<!(?<a>\\d){3})f/",
"(?<!a)/",
"(?<!a)/u",
"(a)/",
"\\k<a>/",
// "(?<a>a)\\1/",
// "\\k<a>(?<a>a)/",
// "\\1(?<a>a)/",
// "\\p{ASCII/",
//"/\\p{Emoji}/",
"(?=a){/",
"(?=a){}/",
"(?=a){1,2}/",
"a*/",
"a{/",
"a{1}/",
"a{1,2}/",
"a+?/",
"a{}?/",
// "a{a}?/",
"a{1}?/",
"a{1,?/",
"a{2,1?/",
"👍🚀❇️/",
"./",
"]/",
"{/",
"|/",
"${1,2/",
"(a)\\1/",
"(a)\\2/",
"(a)(a)(a)(a)(a)(a)(a)(a)(a)(a)\\10/",
"\\d/",
"\\s/",
"\\w/",
"\\t/",
"\\cz/",
"\\0/",
"\\u1/",
"\\u123/",
"\\u{a}/",
"\\u{20/",
"\\u{20}/",
"\\u{00000001}/",
"\\377/",
"\\+/",
// "\\)/",
"\\{/",
"\\//",
"[^-a-b-]/",
"[a]/",
"[--]/",
"[a-]/",
"[-a-b-]/",
"[a-b--/]/",
"[\\b-\\n]/",
"[\\D]/",
"[\\0]/",
//"[\\xz]/",
"[\\x12]/",
// "[\\u]/",
// "[\\u12]/",
// "[\\u{]/",
"[\\/]/",
"[\\S-\\uFFFF]/",
// "[\\u0000-\\s]/",
// "[\\u0000-\\S]/",
// "[\\a-\\z]/",
    ];

    for (const arg of ValidNonUnicodeCases) {
      pass(`Pass ${arg}`, {
        name: `${arg}`,
        source: `${arg}`,
        value: 'foo',
        raw: 'foo',
        context: Context.OptionsAnnexB,
        token: Token.Identifier,
        line: 1,
        column: 3,
    });
    }
  });


});
